// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `addr_decode` from `addr_decode.sv`.
module addr_decode_wrapper #(
parameter int unsigned NoIndices = 32'd0,
  parameter int unsigned NoRules   = 32'd0,
  parameter int unsigned addr_t_WIDTH = 1,
  parameter int unsigned rule_t_WIDTH = 1,
  parameter bit          Napot     = 0,
  parameter int unsigned IdxWidth  = cf_math_pkg::idx_width(NoIndices),
  parameter int unsigned idx_t_WIDTH = 1
) (
input  logic [addr_t_WIDTH-1:0]               addr_i,
  input  logic [rule_t_WIDTH-1:0] [NoRules-1:0] addr_map_i,
  output logic [idx_t_WIDTH-1:0]                idx_o,
  output logic                dec_valid_o,
  output logic                dec_error_o,
  input  logic                en_default_idx_i,
  input  logic [idx_t_WIDTH-1:0]                default_idx_i
);

  addr_decode #(
    .NoIndices ( NoIndices ),
    .NoRules ( NoRules ),
    .addr_t ( logic [addr_t_WIDTH-1:0] ),
    .rule_t ( logic [rule_t_WIDTH-1:0] ),
    .Napot ( Napot ),
    .IdxWidth ( IdxWidth ),
    .idx_t ( logic [idx_t_WIDTH-1:0] )
  ) i_addr_decode (
    .addr_i ( addr_i ),
    .addr_map_i ( addr_map_i ),
    .idx_o ( idx_o ),
    .dec_valid_o ( dec_valid_o ),
    .dec_error_o ( dec_error_o ),
    .en_default_idx_i ( en_default_idx_i ),
    .default_idx_i ( default_idx_i )
  );

endmodule
