// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `addr_decode_napot` from `addr_decode_napot.sv`.
module addr_decode_napot_wrapper #(
  parameter int unsigned NoIndices = 32'd0,

  parameter int unsigned NoRules   = 32'd0,

  parameter type         addr_t    = logic,

  parameter type         rule_t    = logic,

  parameter int unsigned IdxWidth  = cf_math_pkg::idx_width(NoIndices),

  parameter type         idx_t     = logic [IdxWidth-1:0]
) (
  addr_i,
  addr_map_i,
  idx_o,
  dec_valid_o,
  dec_error_o,
  en_default_idx_i,
  default_idx_i
);

  typedef addr_t __addr_i_t;
  typedef rule_t [NoRules-1:0] __addr_map_i_t;
  typedef idx_t __idx_o_t;
  typedef logic __dec_valid_o_t;
  typedef logic __dec_error_o_t;
  typedef logic __en_default_idx_i_t;
  typedef idx_t __default_idx_i_t;

  input logic [$bits(__addr_i_t)-1:0] addr_i;
  input logic [$bits(__addr_map_i_t)-1:0] addr_map_i;
  output logic [$bits(__idx_o_t)-1:0] idx_o;
  output logic [$bits(__dec_valid_o_t)-1:0] dec_valid_o;
  output logic [$bits(__dec_error_o_t)-1:0] dec_error_o;
  input logic [$bits(__en_default_idx_i_t)-1:0] en_default_idx_i;
  input logic [$bits(__default_idx_i_t)-1:0] default_idx_i;

  __addr_i_t __addr_i;
  __addr_map_i_t __addr_map_i;
  __idx_o_t __idx_o;
  __dec_valid_o_t __dec_valid_o;
  __dec_error_o_t __dec_error_o;
  __en_default_idx_i_t __en_default_idx_i;
  __default_idx_i_t __default_idx_i;

  assign __addr_i = __addr_i_t'(addr_i);
  assign __addr_map_i = __addr_map_i_t'(addr_map_i);
  assign idx_o = logic [$bits(__idx_o_t)-1:0]'(__idx_o);
  assign dec_valid_o = logic [$bits(__dec_valid_o_t)-1:0]'(__dec_valid_o);
  assign dec_error_o = logic [$bits(__dec_error_o_t)-1:0]'(__dec_error_o);
  assign __en_default_idx_i = __en_default_idx_i_t'(en_default_idx_i);
  assign __default_idx_i = __default_idx_i_t'(default_idx_i);

  addr_decode_napot #(
    .NoIndices ( NoIndices ),
    .NoRules ( NoRules ),
    .addr_t ( addr_t ),
    .rule_t ( rule_t ),
    .IdxWidth ( IdxWidth ),
    .idx_t ( idx_t )
  ) i_addr_decode_napot (
    .addr_i ( __addr_i ),
    .addr_map_i ( __addr_map_i ),
    .idx_o ( __idx_o ),
    .dec_valid_o ( __dec_valid_o ),
    .dec_error_o ( __dec_error_o ),
    .en_default_idx_i ( __en_default_idx_i ),
    .default_idx_i ( __default_idx_i )
  );

endmodule
