// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `addr_decode_dync` from `addr_decode_dync.sv`.
module addr_decode_dync_wrapper #(
parameter int unsigned NoIndices = 32'd0,

  parameter int unsigned NoRules   = 32'd0,

  parameter type         addr_t    = logic,


















  parameter type         rule_t    = logic,

  parameter bit          Napot     = 0,



  parameter int unsigned IdxWidth  = cf_math_pkg::idx_width(NoIndices),
  parameter type         idx_t     = logic [IdxWidth-1:0]
) (
input  addr_t               addr_i,

  input  rule_t [NoRules-1:0] addr_map_i,

  output idx_t                idx_o,

  output logic                dec_valid_o,

  output logic                dec_error_o,



  input  logic                en_default_idx_i,





  input  idx_t                default_idx_i,


  input  logic                config_ongoing_i
);

  addr_decode_dync #(
    .NoIndices ( NoIndices ),
    .NoRules ( NoRules ),
    .addr_t ( addr_t ),
    .rule_t ( rule_t ),
    .Napot ( Napot ),
    .IdxWidth ( IdxWidth ),
    .idx_t ( idx_t )
  ) i_addr_decode_dync (
    .addr_i ( addr_i ),
    .addr_map_i ( addr_map_i ),
    .idx_o ( idx_o ),
    .dec_valid_o ( dec_valid_o ),
    .dec_error_o ( dec_error_o ),
    .en_default_idx_i ( en_default_idx_i ),
    .default_idx_i ( default_idx_i ),
    .config_ongoing_i ( config_ongoing_i )
  );

endmodule
