// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `binary_to_gray` from `binary_to_gray.sv`.
module binary_to_gray_wrapper #(
    parameter int N = -1
) (
  A,
  Z
);

  typedef logic [N-1:0] __A_t;
  typedef logic [N-1:0] __Z_t;

  input logic [$bits(__A_t)-1:0] A;
  output logic [$bits(__Z_t)-1:0] Z;

  __A_t __A;
  __Z_t __Z;

  assign __A = __A_t'(A);
  assign Z = logic [$bits(__Z_t)-1:0]'(__Z);

  binary_to_gray #(
    .N ( N )
  ) i_binary_to_gray (
    .A ( __A ),
    .Z ( __Z )
  );

endmodule
