// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `boxcar` from `boxcar.sv`.
module boxcar_wrapper #(
    parameter int unsigned Width = 32,

    localparam int unsigned IdxWidth = cf_math_pkg::idx_width(Width),
    localparam type idx_t = logic [IdxWidth-1:0],
    localparam type mask_t = logic [Width-1:0]
) (
  lsb_i,
  msb_i,
  mask_o
);

  typedef idx_t __lsb_i_t;
  typedef idx_t __msb_i_t;
  typedef mask_t __mask_o_t;

  input logic [$bits(__lsb_i_t)-1:0] lsb_i;
  input logic [$bits(__msb_i_t)-1:0] msb_i;
  output logic [$bits(__mask_o_t)-1:0] mask_o;

  __lsb_i_t __lsb_i;
  __msb_i_t __msb_i;
  __mask_o_t __mask_o;

  assign __lsb_i = __lsb_i_t'(lsb_i);
  assign __msb_i = __msb_i_t'(msb_i);
  assign mask_o = logic [$bits(__mask_o_t)-1:0]'(__mask_o);

  boxcar #(
    .Width ( Width )
  ) i_boxcar (
    .lsb_i ( __lsb_i ),
    .msb_i ( __msb_i ),
    .mask_o ( __mask_o )
  );

endmodule
