// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `cb_filter` from `cb_filter.sv`.
module cb_filter_wrapper #(
parameter int unsigned KHashes     =  32'd3,
  parameter int unsigned HashWidth   =  32'd4,
  parameter int unsigned HashRounds  =  32'd1,
  parameter int unsigned InpWidth    =  32'd32,
  parameter int unsigned BucketWidth =  32'd4,

  parameter cb_filter_pkg::cb_seed_t [KHashes-1:0] Seeds = cb_filter_pkg::EgSeeds
) (
input  logic                 clk_i,
  input  logic                 rst_ni,

  input  logic [InpWidth-1:0]  look_data_i,
  output logic                 look_valid_o,

  input  logic [InpWidth-1:0]  incr_data_i,
  input  logic                 incr_valid_i,

  input  logic [InpWidth-1:0]  decr_data_i,
  input  logic                 decr_valid_i,

  input  logic                 filter_clear_i,
  output logic [HashWidth-1:0] filter_usage_o,
  output logic                 filter_full_o,
  output logic                 filter_empty_o,
  output logic                 filter_error_o
);

  cb_filter #(
    .KHashes ( KHashes ),
    .HashWidth ( HashWidth ),
    .HashRounds ( HashRounds ),
    .InpWidth ( InpWidth ),
    .BucketWidth ( BucketWidth ),
    .Seeds ( Seeds )
  ) i_cb_filter (
    .*
  );

endmodule
