// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `cb_filter` from `cb_filter.sv`.
module cb_filter_wrapper #(
  parameter int unsigned KHashes     =  32'd3,
  parameter int unsigned HashWidth   =  32'd4,
  parameter int unsigned HashRounds  =  32'd1,
  parameter int unsigned InpWidth    =  32'd32,
  parameter int unsigned BucketWidth =  32'd4,

  parameter cb_filter_pkg::cb_seed_t [KHashes-1:0] Seeds = cb_filter_pkg::EgSeeds
) (
  clk_i,
  rst_ni,
  look_data_i,
  look_valid_o,
  incr_data_i,
  incr_valid_i,
  decr_data_i,
  decr_valid_i,
  filter_clear_i,
  filter_usage_o,
  filter_full_o,
  filter_empty_o,
  filter_error_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic [InpWidth-1:0] __look_data_i_t;
  typedef logic __look_valid_o_t;
  typedef logic [InpWidth-1:0] __incr_data_i_t;
  typedef logic __incr_valid_i_t;
  typedef logic [InpWidth-1:0] __decr_data_i_t;
  typedef logic __decr_valid_i_t;
  typedef logic __filter_clear_i_t;
  typedef logic [HashWidth-1:0] __filter_usage_o_t;
  typedef logic __filter_full_o_t;
  typedef logic __filter_empty_o_t;
  typedef logic __filter_error_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__look_data_i_t)-1:0] look_data_i;
  output logic [$bits(__look_valid_o_t)-1:0] look_valid_o;
  input logic [$bits(__incr_data_i_t)-1:0] incr_data_i;
  input logic [$bits(__incr_valid_i_t)-1:0] incr_valid_i;
  input logic [$bits(__decr_data_i_t)-1:0] decr_data_i;
  input logic [$bits(__decr_valid_i_t)-1:0] decr_valid_i;
  input logic [$bits(__filter_clear_i_t)-1:0] filter_clear_i;
  output logic [$bits(__filter_usage_o_t)-1:0] filter_usage_o;
  output logic [$bits(__filter_full_o_t)-1:0] filter_full_o;
  output logic [$bits(__filter_empty_o_t)-1:0] filter_empty_o;
  output logic [$bits(__filter_error_o_t)-1:0] filter_error_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __look_data_i_t __look_data_i;
  __look_valid_o_t __look_valid_o;
  __incr_data_i_t __incr_data_i;
  __incr_valid_i_t __incr_valid_i;
  __decr_data_i_t __decr_data_i;
  __decr_valid_i_t __decr_valid_i;
  __filter_clear_i_t __filter_clear_i;
  __filter_usage_o_t __filter_usage_o;
  __filter_full_o_t __filter_full_o;
  __filter_empty_o_t __filter_empty_o;
  __filter_error_o_t __filter_error_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __look_data_i = __look_data_i_t'(look_data_i);
  assign look_valid_o = logic [$bits(__look_valid_o_t)-1:0]'(__look_valid_o);
  assign __incr_data_i = __incr_data_i_t'(incr_data_i);
  assign __incr_valid_i = __incr_valid_i_t'(incr_valid_i);
  assign __decr_data_i = __decr_data_i_t'(decr_data_i);
  assign __decr_valid_i = __decr_valid_i_t'(decr_valid_i);
  assign __filter_clear_i = __filter_clear_i_t'(filter_clear_i);
  assign filter_usage_o = logic [$bits(__filter_usage_o_t)-1:0]'(__filter_usage_o);
  assign filter_full_o = logic [$bits(__filter_full_o_t)-1:0]'(__filter_full_o);
  assign filter_empty_o = logic [$bits(__filter_empty_o_t)-1:0]'(__filter_empty_o);
  assign filter_error_o = logic [$bits(__filter_error_o_t)-1:0]'(__filter_error_o);

  cb_filter #(
    .KHashes ( KHashes ),
    .HashWidth ( HashWidth ),
    .HashRounds ( HashRounds ),
    .InpWidth ( InpWidth ),
    .BucketWidth ( BucketWidth ),
    .Seeds ( Seeds )
  ) i_cb_filter (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .look_data_i ( __look_data_i ),
    .look_valid_o ( __look_valid_o ),
    .incr_data_i ( __incr_data_i ),
    .incr_valid_i ( __incr_valid_i ),
    .decr_data_i ( __decr_data_i ),
    .decr_valid_i ( __decr_valid_i ),
    .filter_clear_i ( __filter_clear_i ),
    .filter_usage_o ( __filter_usage_o ),
    .filter_full_o ( __filter_full_o ),
    .filter_empty_o ( __filter_empty_o ),
    .filter_error_o ( __filter_error_o )
  );

endmodule
