// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `cc_onehot` from `cc_onehot.sv`.
module cc_onehot_wrapper #(
  parameter int unsigned Width = 4
) (
  d_i,
  is_onehot_o
);

  typedef logic [Width-1:0] __d_i_t;
  typedef logic __is_onehot_o_t;

  input logic [$bits(__d_i_t)-1:0] d_i;
  output logic [$bits(__is_onehot_o_t)-1:0] is_onehot_o;

  __d_i_t __d_i;
  __is_onehot_o_t __is_onehot_o;

  assign __d_i = __d_i_t'(d_i);
  assign is_onehot_o = logic [$bits(__is_onehot_o_t)-1:0]'(__is_onehot_o);

  cc_onehot #(
    .Width ( Width )
  ) i_cc_onehot (
    .d_i ( __d_i ),
    .is_onehot_o ( __is_onehot_o )
  );

endmodule
