// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `cc_onehot` from `cc_onehot.sv`.
module cc_onehot_wrapper #(
parameter int unsigned Width = 4
) (
input  logic [Width-1:0] d_i,
  output logic is_onehot_o
);

  cc_onehot #(
    .Width ( Width )
  ) i_cc_onehot (
    .d_i ( d_i ),
    .is_onehot_o ( is_onehot_o )
  );

endmodule
