// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `cdc_reset_ctrlr` from `cdc_reset_ctrlr.sv`.
module cdc_reset_ctrlr_wrapper
  import cdc_reset_ctrlr_pkg::*;
 #(
  parameter int unsigned SYNC_STAGES = 2,

  parameter logic        CLEAR_ON_ASYNC_RESET = 1'b1
) (
  a_clk_i,
  a_rst_ni,
  a_clear_i,
  a_clear_o,
  a_clear_ack_i,
  a_isolate_o,
  a_isolate_ack_i,
  b_clk_i,
  b_rst_ni,
  b_clear_i,
  b_clear_o,
  b_clear_ack_i,
  b_isolate_o,
  b_isolate_ack_i
);

  typedef logic __a_clk_i_t;
  typedef logic __a_rst_ni_t;
  typedef logic __a_clear_i_t;
  typedef logic __a_clear_o_t;
  typedef logic __a_clear_ack_i_t;
  typedef logic __a_isolate_o_t;
  typedef logic __a_isolate_ack_i_t;
  typedef logic __b_clk_i_t;
  typedef logic __b_rst_ni_t;
  typedef logic __b_clear_i_t;
  typedef logic __b_clear_o_t;
  typedef logic __b_clear_ack_i_t;
  typedef logic __b_isolate_o_t;
  typedef logic __b_isolate_ack_i_t;

  input logic [$bits(__a_clk_i_t)-1:0] a_clk_i;
  input logic [$bits(__a_rst_ni_t)-1:0] a_rst_ni;
  input logic [$bits(__a_clear_i_t)-1:0] a_clear_i;
  output logic [$bits(__a_clear_o_t)-1:0] a_clear_o;
  input logic [$bits(__a_clear_ack_i_t)-1:0] a_clear_ack_i;
  output logic [$bits(__a_isolate_o_t)-1:0] a_isolate_o;
  input logic [$bits(__a_isolate_ack_i_t)-1:0] a_isolate_ack_i;
  input logic [$bits(__b_clk_i_t)-1:0] b_clk_i;
  input logic [$bits(__b_rst_ni_t)-1:0] b_rst_ni;
  input logic [$bits(__b_clear_i_t)-1:0] b_clear_i;
  output logic [$bits(__b_clear_o_t)-1:0] b_clear_o;
  input logic [$bits(__b_clear_ack_i_t)-1:0] b_clear_ack_i;
  output logic [$bits(__b_isolate_o_t)-1:0] b_isolate_o;
  input logic [$bits(__b_isolate_ack_i_t)-1:0] b_isolate_ack_i;

  __a_clk_i_t __a_clk_i;
  __a_rst_ni_t __a_rst_ni;
  __a_clear_i_t __a_clear_i;
  __a_clear_o_t __a_clear_o;
  __a_clear_ack_i_t __a_clear_ack_i;
  __a_isolate_o_t __a_isolate_o;
  __a_isolate_ack_i_t __a_isolate_ack_i;
  __b_clk_i_t __b_clk_i;
  __b_rst_ni_t __b_rst_ni;
  __b_clear_i_t __b_clear_i;
  __b_clear_o_t __b_clear_o;
  __b_clear_ack_i_t __b_clear_ack_i;
  __b_isolate_o_t __b_isolate_o;
  __b_isolate_ack_i_t __b_isolate_ack_i;

  assign __a_clk_i = __a_clk_i_t'(a_clk_i);
  assign __a_rst_ni = __a_rst_ni_t'(a_rst_ni);
  assign __a_clear_i = __a_clear_i_t'(a_clear_i);
  assign a_clear_o = logic [$bits(__a_clear_o_t)-1:0]'(__a_clear_o);
  assign __a_clear_ack_i = __a_clear_ack_i_t'(a_clear_ack_i);
  assign a_isolate_o = logic [$bits(__a_isolate_o_t)-1:0]'(__a_isolate_o);
  assign __a_isolate_ack_i = __a_isolate_ack_i_t'(a_isolate_ack_i);
  assign __b_clk_i = __b_clk_i_t'(b_clk_i);
  assign __b_rst_ni = __b_rst_ni_t'(b_rst_ni);
  assign __b_clear_i = __b_clear_i_t'(b_clear_i);
  assign b_clear_o = logic [$bits(__b_clear_o_t)-1:0]'(__b_clear_o);
  assign __b_clear_ack_i = __b_clear_ack_i_t'(b_clear_ack_i);
  assign b_isolate_o = logic [$bits(__b_isolate_o_t)-1:0]'(__b_isolate_o);
  assign __b_isolate_ack_i = __b_isolate_ack_i_t'(b_isolate_ack_i);

  cdc_reset_ctrlr #(
    .SYNC_STAGES ( SYNC_STAGES ),
    .CLEAR_ON_ASYNC_RESET ( CLEAR_ON_ASYNC_RESET )
  ) i_cdc_reset_ctrlr (
    .a_clk_i ( __a_clk_i ),
    .a_rst_ni ( __a_rst_ni ),
    .a_clear_i ( __a_clear_i ),
    .a_clear_o ( __a_clear_o ),
    .a_clear_ack_i ( __a_clear_ack_i ),
    .a_isolate_o ( __a_isolate_o ),
    .a_isolate_ack_i ( __a_isolate_ack_i ),
    .b_clk_i ( __b_clk_i ),
    .b_rst_ni ( __b_rst_ni ),
    .b_clear_i ( __b_clear_i ),
    .b_clear_o ( __b_clear_o ),
    .b_clear_ack_i ( __b_clear_ack_i ),
    .b_isolate_o ( __b_isolate_o ),
    .b_isolate_ack_i ( __b_isolate_ack_i )
  );

endmodule
