// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `cdc_reset_ctrlr` from `cdc_reset_ctrlr.sv`.
module cdc_reset_ctrlr_wrapper
  import cdc_reset_ctrlr_pkg::*;
 #(
parameter int unsigned SYNC_STAGES = 2,


  parameter logic        CLEAR_ON_ASYNC_RESET = 1'b1
) (
input logic  a_clk_i,
  input logic  a_rst_ni,
  input logic  a_clear_i,
  output logic a_clear_o,
  input logic a_clear_ack_i,
  output logic a_isolate_o,
  input logic  a_isolate_ack_i,

  input logic  b_clk_i,
  input logic  b_rst_ni,
  input logic  b_clear_i,
  output logic b_clear_o,
  input logic  b_clear_ack_i,
  output logic b_isolate_o,
  input logic  b_isolate_ack_i
);

  cdc_reset_ctrlr #(
    .SYNC_STAGES ( SYNC_STAGES ),
    .CLEAR_ON_ASYNC_RESET ( CLEAR_ON_ASYNC_RESET )
  ) i_cdc_reset_ctrlr (
    .a_clk_i ( a_clk_i ),
    .a_rst_ni ( a_rst_ni ),
    .a_clear_i ( a_clear_i ),
    .a_clear_o ( a_clear_o ),
    .a_clear_ack_i ( a_clear_ack_i ),
    .a_isolate_o ( a_isolate_o ),
    .a_isolate_ack_i ( a_isolate_ack_i ),
    .b_clk_i ( b_clk_i ),
    .b_rst_ni ( b_rst_ni ),
    .b_clear_i ( b_clear_i ),
    .b_clear_o ( b_clear_o ),
    .b_clear_ack_i ( b_clear_ack_i ),
    .b_isolate_o ( b_isolate_o ),
    .b_isolate_ack_i ( b_isolate_ack_i )
  );

endmodule
