// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `cdc_2phase` from `cdc_2phase.sv`.
module cdc_2phase_wrapper #(
  parameter type T = logic
) (
  src_rst_ni,
  src_clk_i,
  src_data_i,
  src_valid_i,
  src_ready_o,
  dst_rst_ni,
  dst_clk_i,
  dst_data_o,
  dst_valid_o,
  dst_ready_i
);

  typedef logic __src_rst_ni_t;
  typedef logic __src_clk_i_t;
  typedef T __src_data_i_t;
  typedef logic __src_valid_i_t;
  typedef logic __src_ready_o_t;
  typedef logic __dst_rst_ni_t;
  typedef logic __dst_clk_i_t;
  typedef T __dst_data_o_t;
  typedef logic __dst_valid_o_t;
  typedef logic __dst_ready_i_t;

  input logic [$bits(__src_rst_ni_t)-1:0] src_rst_ni;
  input logic [$bits(__src_clk_i_t)-1:0] src_clk_i;
  input logic [$bits(__src_data_i_t)-1:0] src_data_i;
  input logic [$bits(__src_valid_i_t)-1:0] src_valid_i;
  output logic [$bits(__src_ready_o_t)-1:0] src_ready_o;
  input logic [$bits(__dst_rst_ni_t)-1:0] dst_rst_ni;
  input logic [$bits(__dst_clk_i_t)-1:0] dst_clk_i;
  output logic [$bits(__dst_data_o_t)-1:0] dst_data_o;
  output logic [$bits(__dst_valid_o_t)-1:0] dst_valid_o;
  input logic [$bits(__dst_ready_i_t)-1:0] dst_ready_i;

  __src_rst_ni_t __src_rst_ni;
  __src_clk_i_t __src_clk_i;
  __src_data_i_t __src_data_i;
  __src_valid_i_t __src_valid_i;
  __src_ready_o_t __src_ready_o;
  __dst_rst_ni_t __dst_rst_ni;
  __dst_clk_i_t __dst_clk_i;
  __dst_data_o_t __dst_data_o;
  __dst_valid_o_t __dst_valid_o;
  __dst_ready_i_t __dst_ready_i;

  assign __src_rst_ni = __src_rst_ni_t'(src_rst_ni);
  assign __src_clk_i = __src_clk_i_t'(src_clk_i);
  assign __src_data_i = __src_data_i_t'(src_data_i);
  assign __src_valid_i = __src_valid_i_t'(src_valid_i);
  assign src_ready_o = logic [$bits(__src_ready_o_t)-1:0]'(__src_ready_o);
  assign __dst_rst_ni = __dst_rst_ni_t'(dst_rst_ni);
  assign __dst_clk_i = __dst_clk_i_t'(dst_clk_i);
  assign dst_data_o = logic [$bits(__dst_data_o_t)-1:0]'(__dst_data_o);
  assign dst_valid_o = logic [$bits(__dst_valid_o_t)-1:0]'(__dst_valid_o);
  assign __dst_ready_i = __dst_ready_i_t'(dst_ready_i);

  cdc_2phase #(
    .T ( T )
  ) i_cdc_2phase (
    .src_rst_ni ( __src_rst_ni ),
    .src_clk_i ( __src_clk_i ),
    .src_data_i ( __src_data_i ),
    .src_valid_i ( __src_valid_i ),
    .src_ready_o ( __src_ready_o ),
    .dst_rst_ni ( __dst_rst_ni ),
    .dst_clk_i ( __dst_clk_i ),
    .dst_data_o ( __dst_data_o ),
    .dst_valid_o ( __dst_valid_o ),
    .dst_ready_i ( __dst_ready_i )
  );

endmodule
