// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `cdc_fifo_gray_clearable` from `cdc_fifo_gray_clearable.sv`.
module cdc_fifo_gray_clearable_wrapper #(
parameter int unsigned WIDTH = 1,
  parameter int unsigned T_WIDTH = 1,
  parameter int LOG_DEPTH = 3,
  parameter int SYNC_STAGES = 3,
  parameter int CLEAR_ON_ASYNC_RESET = 1
) (
input  logic src_rst_ni,
  input  logic src_clk_i,
  input  logic src_clear_i,
  output logic src_clear_pending_o,
  input  logic [T_WIDTH-1:0]     src_data_i,
  input  logic src_valid_i,
  output logic src_ready_o,
  input  logic dst_rst_ni,
  input  logic dst_clk_i,
  input  logic dst_clear_i,
  output logic dst_clear_pending_o,
  output logic [T_WIDTH-1:0]     dst_data_o,
  output logic dst_valid_o,
  input  logic dst_ready_i
);

  cdc_fifo_gray_clearable #(
    .WIDTH ( WIDTH ),
    .T ( logic [T_WIDTH-1:0] ),
    .LOG_DEPTH ( LOG_DEPTH ),
    .SYNC_STAGES ( SYNC_STAGES ),
    .CLEAR_ON_ASYNC_RESET ( CLEAR_ON_ASYNC_RESET )
  ) i_cdc_fifo_gray_clearable (
    .src_rst_ni ( src_rst_ni ),
    .src_clk_i ( src_clk_i ),
    .src_clear_i ( src_clear_i ),
    .src_clear_pending_o ( src_clear_pending_o ),
    .src_data_i ( src_data_i ),
    .src_valid_i ( src_valid_i ),
    .src_ready_o ( src_ready_o ),
    .dst_rst_ni ( dst_rst_ni ),
    .dst_clk_i ( dst_clk_i ),
    .dst_clear_i ( dst_clear_i ),
    .dst_clear_pending_o ( dst_clear_pending_o ),
    .dst_data_o ( dst_data_o ),
    .dst_valid_o ( dst_valid_o ),
    .dst_ready_i ( dst_ready_i )
  );

endmodule
