// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `cdc_fifo_gray` from `cdc_fifo_gray.sv`.
module cdc_fifo_gray_wrapper #(
parameter int unsigned WIDTH = 1,

  parameter type T = logic [WIDTH-1:0],

  parameter int LOG_DEPTH = 3,

  parameter int SYNC_STAGES = 2
) (
input  logic src_rst_ni,
  input  logic src_clk_i,
  input  T     src_data_i,
  input  logic src_valid_i,
  output logic src_ready_o,

  input  logic dst_rst_ni,
  input  logic dst_clk_i,
  output T     dst_data_o,
  output logic dst_valid_o,
  input  logic dst_ready_i
);

  cdc_fifo_gray #(
    .WIDTH ( WIDTH ),
    .T ( T ),
    .LOG_DEPTH ( LOG_DEPTH ),
    .SYNC_STAGES ( SYNC_STAGES )
  ) i_cdc_fifo_gray (
    .*
  );

endmodule
