// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `clk_mux_glitch_free` from `clk_mux_glitch_free.sv`.
module clk_mux_glitch_free_wrapper #(
parameter int unsigned  NUM_INPUTS = 2,
  parameter int unsigned  NUM_SYNC_STAGES = 2,
  parameter bit CLOCK_DURING_RESET = 1'b1,


  localparam int unsigned SelWidth = $clog2(NUM_INPUTS)
) (
input logic [NUM_INPUTS-1:0] clks_i,
   input logic                  test_clk_i,
   input logic                  test_en_i,
   input logic                  async_rstn_i,
   input logic [SelWidth-1:0]   async_sel_i,
   output logic                 clk_o
);

  clk_mux_glitch_free #(
    .NUM_INPUTS ( NUM_INPUTS ),
    .NUM_SYNC_STAGES ( NUM_SYNC_STAGES ),
    .CLOCK_DURING_RESET ( CLOCK_DURING_RESET )
  ) i_clk_mux_glitch_free (
    .clks_i ( clks_i ),
    .test_clk_i ( test_clk_i ),
    .test_en_i ( test_en_i ),
    .async_rstn_i ( async_rstn_i ),
    .async_sel_i ( async_sel_i ),
    .clk_o ( clk_o )
  );

endmodule
