// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `clk_int_div` from `clk_int_div.sv`.
module clk_int_div_wrapper #(
parameter int unsigned DIV_VALUE_WIDTH = 4,
  parameter int unsigned DEFAULT_DIV_VALUE = 0,
  parameter bit          ENABLE_CLOCK_IN_RESET = 1'b0
) (
input logic                        clk_i,
  input logic                        rst_ni,
  input logic                        en_i,
  input logic                        test_mode_en_i,
  input logic [DIV_VALUE_WIDTH-1:0]  div_i,
  input logic                        div_valid_i,
  output logic                       div_ready_o,
  output logic                       clk_o,
  output logic [DIV_VALUE_WIDTH-1:0] cycl_count_o
);

  clk_int_div #(
    .DIV_VALUE_WIDTH ( DIV_VALUE_WIDTH ),
    .DEFAULT_DIV_VALUE ( DEFAULT_DIV_VALUE ),
    .ENABLE_CLOCK_IN_RESET ( ENABLE_CLOCK_IN_RESET )
  ) i_clk_int_div (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .en_i ( en_i ),
    .test_mode_en_i ( test_mode_en_i ),
    .div_i ( div_i ),
    .div_valid_i ( div_valid_i ),
    .div_ready_o ( div_ready_o ),
    .clk_o ( clk_o ),
    .cycl_count_o ( cycl_count_o )
  );

endmodule
