// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `clk_int_div` from `clk_int_div.sv`.
module clk_int_div_wrapper #(
  parameter int unsigned DIV_VALUE_WIDTH = 4,

  parameter int unsigned DEFAULT_DIV_VALUE = 0,

  parameter bit          ENABLE_CLOCK_IN_RESET = 1'b0
) (
  clk_i,
  rst_ni,
  en_i,
  test_mode_en_i,
  div_i,
  div_valid_i,
  div_ready_o,
  clk_o,
  cycl_count_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __en_i_t;
  typedef logic __test_mode_en_i_t;
  typedef logic [DIV_VALUE_WIDTH-1:0] __div_i_t;
  typedef logic __div_valid_i_t;
  typedef logic __div_ready_o_t;
  typedef logic __clk_o_t;
  typedef logic [DIV_VALUE_WIDTH-1:0] __cycl_count_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__en_i_t)-1:0] en_i;
  input logic [$bits(__test_mode_en_i_t)-1:0] test_mode_en_i;
  input logic [$bits(__div_i_t)-1:0] div_i;
  input logic [$bits(__div_valid_i_t)-1:0] div_valid_i;
  output logic [$bits(__div_ready_o_t)-1:0] div_ready_o;
  output logic [$bits(__clk_o_t)-1:0] clk_o;
  output logic [$bits(__cycl_count_o_t)-1:0] cycl_count_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __en_i_t __en_i;
  __test_mode_en_i_t __test_mode_en_i;
  __div_i_t __div_i;
  __div_valid_i_t __div_valid_i;
  __div_ready_o_t __div_ready_o;
  __clk_o_t __clk_o;
  __cycl_count_o_t __cycl_count_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __en_i = __en_i_t'(en_i);
  assign __test_mode_en_i = __test_mode_en_i_t'(test_mode_en_i);
  assign __div_i = __div_i_t'(div_i);
  assign __div_valid_i = __div_valid_i_t'(div_valid_i);
  assign div_ready_o = logic [$bits(__div_ready_o_t)-1:0]'(__div_ready_o);
  assign clk_o = logic [$bits(__clk_o_t)-1:0]'(__clk_o);
  assign cycl_count_o = logic [$bits(__cycl_count_o_t)-1:0]'(__cycl_count_o);

  clk_int_div #(
    .DIV_VALUE_WIDTH ( DIV_VALUE_WIDTH ),
    .DEFAULT_DIV_VALUE ( DEFAULT_DIV_VALUE ),
    .ENABLE_CLOCK_IN_RESET ( ENABLE_CLOCK_IN_RESET )
  ) i_clk_int_div (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .en_i ( __en_i ),
    .test_mode_en_i ( __test_mode_en_i ),
    .div_i ( __div_i ),
    .div_valid_i ( __div_valid_i ),
    .div_ready_o ( __div_ready_o ),
    .clk_o ( __clk_o ),
    .cycl_count_o ( __cycl_count_o )
  );

endmodule
