// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `clk_mux_glitch_free` from `clk_mux_glitch_free.sv`.
module clk_mux_glitch_free_wrapper #(
  parameter int unsigned  NUM_INPUTS = 2,
  parameter int unsigned  NUM_SYNC_STAGES = 2,
  parameter bit CLOCK_DURING_RESET = 1'b1,

  localparam int unsigned SelWidth = $clog2(NUM_INPUTS)
) (
  clks_i,
  test_clk_i,
  test_en_i,
  async_rstn_i,
  async_sel_i,
  clk_o
);

  typedef logic [NUM_INPUTS-1:0] __clks_i_t;
  typedef logic __test_clk_i_t;
  typedef logic __test_en_i_t;
  typedef logic __async_rstn_i_t;
  typedef logic [SelWidth-1:0] __async_sel_i_t;
  typedef logic __clk_o_t;

  input logic [$bits(__clks_i_t)-1:0] clks_i;
  input logic [$bits(__test_clk_i_t)-1:0] test_clk_i;
  input logic [$bits(__test_en_i_t)-1:0] test_en_i;
  input logic [$bits(__async_rstn_i_t)-1:0] async_rstn_i;
  input logic [$bits(__async_sel_i_t)-1:0] async_sel_i;
  output logic [$bits(__clk_o_t)-1:0] clk_o;

  __clks_i_t __clks_i;
  __test_clk_i_t __test_clk_i;
  __test_en_i_t __test_en_i;
  __async_rstn_i_t __async_rstn_i;
  __async_sel_i_t __async_sel_i;
  __clk_o_t __clk_o;

  assign __clks_i = __clks_i_t'(clks_i);
  assign __test_clk_i = __test_clk_i_t'(test_clk_i);
  assign __test_en_i = __test_en_i_t'(test_en_i);
  assign __async_rstn_i = __async_rstn_i_t'(async_rstn_i);
  assign __async_sel_i = __async_sel_i_t'(async_sel_i);
  assign clk_o = logic [$bits(__clk_o_t)-1:0]'(__clk_o);

  clk_mux_glitch_free #(
    .NUM_INPUTS ( NUM_INPUTS ),
    .NUM_SYNC_STAGES ( NUM_SYNC_STAGES ),
    .CLOCK_DURING_RESET ( CLOCK_DURING_RESET )
  ) i_clk_mux_glitch_free (
    .clks_i ( __clks_i ),
    .test_clk_i ( __test_clk_i ),
    .test_en_i ( __test_en_i ),
    .async_rstn_i ( __async_rstn_i ),
    .async_sel_i ( __async_sel_i ),
    .clk_o ( __clk_o )
  );

endmodule
