// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `counter` from `counter.sv`.
module counter_wrapper #(
    parameter int unsigned WIDTH = 4,
    parameter bit STICKY_OVERFLOW = 1'b0
) (
  clk_i,
  rst_ni,
  clear_i,
  en_i,
  load_i,
  down_i,
  d_i,
  q_o,
  overflow_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __clear_i_t;
  typedef logic __en_i_t;
  typedef logic __load_i_t;
  typedef logic __down_i_t;
  typedef logic [WIDTH-1:0] __d_i_t;
  typedef logic [WIDTH-1:0] __q_o_t;
  typedef logic __overflow_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__clear_i_t)-1:0] clear_i;
  input logic [$bits(__en_i_t)-1:0] en_i;
  input logic [$bits(__load_i_t)-1:0] load_i;
  input logic [$bits(__down_i_t)-1:0] down_i;
  input logic [$bits(__d_i_t)-1:0] d_i;
  output logic [$bits(__q_o_t)-1:0] q_o;
  output logic [$bits(__overflow_o_t)-1:0] overflow_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __clear_i_t __clear_i;
  __en_i_t __en_i;
  __load_i_t __load_i;
  __down_i_t __down_i;
  __d_i_t __d_i;
  __q_o_t __q_o;
  __overflow_o_t __overflow_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __clear_i = __clear_i_t'(clear_i);
  assign __en_i = __en_i_t'(en_i);
  assign __load_i = __load_i_t'(load_i);
  assign __down_i = __down_i_t'(down_i);
  assign __d_i = __d_i_t'(d_i);
  assign q_o = logic [$bits(__q_o_t)-1:0]'(__q_o);
  assign overflow_o = logic [$bits(__overflow_o_t)-1:0]'(__overflow_o);

  counter #(
    .WIDTH ( WIDTH ),
    .STICKY_OVERFLOW ( STICKY_OVERFLOW )
  ) i_counter (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .clear_i ( __clear_i ),
    .en_i ( __en_i ),
    .load_i ( __load_i ),
    .down_i ( __down_i ),
    .d_i ( __d_i ),
    .q_o ( __q_o ),
    .overflow_o ( __overflow_o )
  );

endmodule
