// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `credit_counter` from `credit_counter.sv`.
module credit_counter_wrapper #(
  parameter int unsigned NumCredits      = 0,

  parameter bit          InitCreditEmpty = 1'b0,

  parameter int unsigned InitNumCredits  = InitCreditEmpty ? '0 : NumCredits,
  parameter type         credit_cnt_t    = logic [$clog2(NumCredits):0]
) (
  clk_i,
  rst_ni,
  credit_o,
  credit_give_i,
  credit_take_i,
  credit_init_i,
  credit_left_o,
  credit_crit_o,
  credit_full_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef credit_cnt_t __credit_o_t;
  typedef logic __credit_give_i_t;
  typedef logic __credit_take_i_t;
  typedef logic __credit_init_i_t;
  typedef logic __credit_left_o_t;
  typedef logic __credit_crit_o_t;
  typedef logic __credit_full_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  output logic [$bits(__credit_o_t)-1:0] credit_o;
  input logic [$bits(__credit_give_i_t)-1:0] credit_give_i;
  input logic [$bits(__credit_take_i_t)-1:0] credit_take_i;
  input logic [$bits(__credit_init_i_t)-1:0] credit_init_i;
  output logic [$bits(__credit_left_o_t)-1:0] credit_left_o;
  output logic [$bits(__credit_crit_o_t)-1:0] credit_crit_o;
  output logic [$bits(__credit_full_o_t)-1:0] credit_full_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __credit_o_t __credit_o;
  __credit_give_i_t __credit_give_i;
  __credit_take_i_t __credit_take_i;
  __credit_init_i_t __credit_init_i;
  __credit_left_o_t __credit_left_o;
  __credit_crit_o_t __credit_crit_o;
  __credit_full_o_t __credit_full_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign credit_o = logic [$bits(__credit_o_t)-1:0]'(__credit_o);
  assign __credit_give_i = __credit_give_i_t'(credit_give_i);
  assign __credit_take_i = __credit_take_i_t'(credit_take_i);
  assign __credit_init_i = __credit_init_i_t'(credit_init_i);
  assign credit_left_o = logic [$bits(__credit_left_o_t)-1:0]'(__credit_left_o);
  assign credit_crit_o = logic [$bits(__credit_crit_o_t)-1:0]'(__credit_crit_o);
  assign credit_full_o = logic [$bits(__credit_full_o_t)-1:0]'(__credit_full_o);

  credit_counter #(
    .NumCredits ( NumCredits ),
    .InitCreditEmpty ( InitCreditEmpty ),
    .InitNumCredits ( InitNumCredits ),
    .credit_cnt_t ( credit_cnt_t )
  ) i_credit_counter (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .credit_o ( __credit_o ),
    .credit_give_i ( __credit_give_i ),
    .credit_take_i ( __credit_take_i ),
    .credit_init_i ( __credit_init_i ),
    .credit_left_o ( __credit_left_o ),
    .credit_crit_o ( __credit_crit_o ),
    .credit_full_o ( __credit_full_o )
  );

endmodule
