// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `credit_counter` from `credit_counter.sv`.
module credit_counter_wrapper #(
parameter int unsigned NumCredits      = 0,

  parameter bit          InitCreditEmpty = 1'b0,

  parameter int unsigned InitNumCredits  = InitCreditEmpty ? '0 : NumCredits,
  parameter type         credit_cnt_t    = logic [$clog2(NumCredits):0]
) (
input  logic clk_i,
  input  logic rst_ni,

  output credit_cnt_t credit_o,

  input  logic credit_give_i,
  input  logic credit_take_i,
  input  logic credit_init_i,

  output logic credit_left_o,
  output logic credit_crit_o,
  output logic credit_full_o
);

  credit_counter #(
    .NumCredits ( NumCredits ),
    .InitCreditEmpty ( InitCreditEmpty ),
    .InitNumCredits ( InitNumCredits ),
    .credit_cnt_t ( credit_cnt_t )
  ) i_credit_counter (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .credit_o ( credit_o ),
    .credit_give_i ( credit_give_i ),
    .credit_take_i ( credit_take_i ),
    .credit_init_i ( credit_init_i ),
    .credit_left_o ( credit_left_o ),
    .credit_crit_o ( credit_crit_o ),
    .credit_full_o ( credit_full_o )
  );

endmodule
