// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `ecc_encode` from `ecc_encode.sv`.
module ecc_encode_wrapper
  import ecc_pkg::*;
 #(
parameter  int unsigned DataWidth   = 64,
  parameter int unsigned data_t_WIDTH = 1,
  parameter int unsigned parity_t_WIDTH = 1,
  parameter int unsigned code_word_t_WIDTH = 1,
  parameter int unsigned encoded_data_t_WIDTH = 1
) (
input  logic [data_t_WIDTH-1:0]         data_i,
  output logic [encoded_data_t_WIDTH-1:0] data_o
);

  ecc_encode #(
    .DataWidth ( DataWidth ),
    .data_t ( logic [data_t_WIDTH-1:0] ),
    .parity_t ( logic [parity_t_WIDTH-1:0] ),
    .code_word_t ( logic [code_word_t_WIDTH-1:0] ),
    .encoded_data_t ( logic [encoded_data_t_WIDTH-1:0] )
  ) i_ecc_encode (
    .data_i ( data_i ),
    .data_o ( data_o )
  );

endmodule
