// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `ecc_decode` from `ecc_decode.sv`.
module ecc_decode_wrapper
  import ecc_pkg::*;
 #(
  parameter  int unsigned DataWidth   = 64,

  parameter type data_t         = logic [DataWidth-1:0],
  parameter type parity_t       = logic [get_parity_width(DataWidth)-1:0],
  parameter type code_word_t    = logic [get_cw_width(DataWidth)-1:0],
  parameter type encoded_data_t = struct packed {
                                    logic parity;
                                    code_word_t code_word;
                                  }
) (
  data_i,
  data_o,
  syndrome_o,
  single_error_o,
  parity_error_o,
  double_error_o
);

  typedef encoded_data_t __data_i_t;
  typedef data_t __data_o_t;
  typedef parity_t __syndrome_o_t;
  typedef logic __single_error_o_t;
  typedef logic __parity_error_o_t;
  typedef logic __double_error_o_t;

  input logic [$bits(__data_i_t)-1:0] data_i;
  output logic [$bits(__data_o_t)-1:0] data_o;
  output logic [$bits(__syndrome_o_t)-1:0] syndrome_o;
  output logic [$bits(__single_error_o_t)-1:0] single_error_o;
  output logic [$bits(__parity_error_o_t)-1:0] parity_error_o;
  output logic [$bits(__double_error_o_t)-1:0] double_error_o;

  __data_i_t __data_i;
  __data_o_t __data_o;
  __syndrome_o_t __syndrome_o;
  __single_error_o_t __single_error_o;
  __parity_error_o_t __parity_error_o;
  __double_error_o_t __double_error_o;

  assign __data_i = __data_i_t'(data_i);
  assign data_o = logic [$bits(__data_o_t)-1:0]'(__data_o);
  assign syndrome_o = logic [$bits(__syndrome_o_t)-1:0]'(__syndrome_o);
  assign single_error_o = logic [$bits(__single_error_o_t)-1:0]'(__single_error_o);
  assign parity_error_o = logic [$bits(__parity_error_o_t)-1:0]'(__parity_error_o);
  assign double_error_o = logic [$bits(__double_error_o_t)-1:0]'(__double_error_o);

  ecc_decode #(
    .DataWidth ( DataWidth ),
    .data_t ( data_t ),
    .parity_t ( parity_t ),
    .code_word_t ( code_word_t ),
    .encoded_data_t ( encoded_data_t )
  ) i_ecc_decode (
    .data_i ( __data_i ),
    .data_o ( __data_o ),
    .syndrome_o ( __syndrome_o ),
    .single_error_o ( __single_error_o ),
    .parity_error_o ( __parity_error_o ),
    .double_error_o ( __double_error_o )
  );

endmodule
