// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `ecc_decode` from `ecc_decode.sv`.
module ecc_decode_wrapper
  import ecc_pkg::*;
 #(
parameter  int unsigned DataWidth   = 64,

  parameter type data_t         = logic [DataWidth-1:0],
  parameter type parity_t       = logic [get_parity_width(DataWidth)-1:0],
  parameter type code_word_t    = logic [get_cw_width(DataWidth)-1:0],
  parameter type encoded_data_t = struct packed {
                                    logic parity;
                                    code_word_t code_word;
                                  }
) (
input  encoded_data_t data_i,

  output data_t         data_o,

  output parity_t       syndrome_o,

  output logic          single_error_o,

  output logic          parity_error_o,

  output logic          double_error_o
);

  ecc_decode #(
    .DataWidth ( DataWidth ),
    .data_t ( data_t ),
    .parity_t ( parity_t ),
    .code_word_t ( code_word_t ),
    .encoded_data_t ( encoded_data_t )
  ) i_ecc_decode (
    .data_i ( data_i ),
    .data_o ( data_o ),
    .syndrome_o ( syndrome_o ),
    .single_error_o ( single_error_o ),
    .parity_error_o ( parity_error_o ),
    .double_error_o ( double_error_o )
  );

endmodule
