// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `edge_propagator_ack` from `edge_propagator_ack.sv`.
module edge_propagator_ack_wrapper (
  clk_tx_i,
  rstn_tx_i,
  edge_i,
  ack_tx_o,
  clk_rx_i,
  rstn_rx_i,
  edge_o
);

  typedef logic __clk_tx_i_t;
  typedef logic __rstn_tx_i_t;
  typedef logic __edge_i_t;
  typedef logic __ack_tx_o_t;
  typedef logic __clk_rx_i_t;
  typedef logic __rstn_rx_i_t;
  typedef logic __edge_o_t;

  input logic [$bits(__clk_tx_i_t)-1:0] clk_tx_i;
  input logic [$bits(__rstn_tx_i_t)-1:0] rstn_tx_i;
  input logic [$bits(__edge_i_t)-1:0] edge_i;
  output logic [$bits(__ack_tx_o_t)-1:0] ack_tx_o;
  input logic [$bits(__clk_rx_i_t)-1:0] clk_rx_i;
  input logic [$bits(__rstn_rx_i_t)-1:0] rstn_rx_i;
  output logic [$bits(__edge_o_t)-1:0] edge_o;

  __clk_tx_i_t __clk_tx_i;
  __rstn_tx_i_t __rstn_tx_i;
  __edge_i_t __edge_i;
  __ack_tx_o_t __ack_tx_o;
  __clk_rx_i_t __clk_rx_i;
  __rstn_rx_i_t __rstn_rx_i;
  __edge_o_t __edge_o;

  assign __clk_tx_i = __clk_tx_i_t'(clk_tx_i);
  assign __rstn_tx_i = __rstn_tx_i_t'(rstn_tx_i);
  assign __edge_i = __edge_i_t'(edge_i);
  assign ack_tx_o = logic [$bits(__ack_tx_o_t)-1:0]'(__ack_tx_o);
  assign __clk_rx_i = __clk_rx_i_t'(clk_rx_i);
  assign __rstn_rx_i = __rstn_rx_i_t'(rstn_rx_i);
  assign edge_o = logic [$bits(__edge_o_t)-1:0]'(__edge_o);

  edge_propagator_ack i_edge_propagator_ack (
    .clk_tx_i ( __clk_tx_i ),
    .rstn_tx_i ( __rstn_tx_i ),
    .edge_i ( __edge_i ),
    .ack_tx_o ( __ack_tx_o ),
    .clk_rx_i ( __clk_rx_i ),
    .rstn_rx_i ( __rstn_rx_i ),
    .edge_o ( __edge_o )
  );

endmodule
