// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `edge_propagator` from `edge_propagator.sv`.
module edge_propagator_wrapper (
input  logic clk_tx_i,
  input  logic rstn_tx_i,
  input  logic edge_i,
  input  logic clk_rx_i,
  input  logic rstn_rx_i,
  output logic edge_o
);

  edge_propagator i_edge_propagator (
    .clk_tx_i ( clk_tx_i ),
    .rstn_tx_i ( rstn_tx_i ),
    .edge_i ( edge_i ),
    .clk_rx_i ( clk_rx_i ),
    .rstn_rx_i ( rstn_rx_i ),
    .edge_o ( edge_o )
  );

endmodule
