// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `edge_detect` from `edge_detect.sv`.
module edge_detect_wrapper (
  clk_i,
  rst_ni,
  d_i,
  re_o,
  fe_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __d_i_t;
  typedef logic __re_o_t;
  typedef logic __fe_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__d_i_t)-1:0] d_i;
  output logic [$bits(__re_o_t)-1:0] re_o;
  output logic [$bits(__fe_o_t)-1:0] fe_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __d_i_t __d_i;
  __re_o_t __re_o;
  __fe_o_t __fe_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __d_i = __d_i_t'(d_i);
  assign re_o = logic [$bits(__re_o_t)-1:0]'(__re_o);
  assign fe_o = logic [$bits(__fe_o_t)-1:0]'(__fe_o);

  edge_detect i_edge_detect (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .d_i ( __d_i ),
    .re_o ( __re_o ),
    .fe_o ( __fe_o )
  );

endmodule
