// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `edge_propagator_rx` from `edge_propagator_rx.sv`.
module edge_propagator_rx_wrapper (
  clk_i,
  rstn_i,
  valid_i,
  ack_o,
  valid_o
);

  typedef logic __clk_i_t;
  typedef logic __rstn_i_t;
  typedef logic __valid_i_t;
  typedef logic __ack_o_t;
  typedef logic __valid_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rstn_i_t)-1:0] rstn_i;
  input logic [$bits(__valid_i_t)-1:0] valid_i;
  output logic [$bits(__ack_o_t)-1:0] ack_o;
  output logic [$bits(__valid_o_t)-1:0] valid_o;

  __clk_i_t __clk_i;
  __rstn_i_t __rstn_i;
  __valid_i_t __valid_i;
  __ack_o_t __ack_o;
  __valid_o_t __valid_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rstn_i = __rstn_i_t'(rstn_i);
  assign __valid_i = __valid_i_t'(valid_i);
  assign ack_o = logic [$bits(__ack_o_t)-1:0]'(__ack_o);
  assign valid_o = logic [$bits(__valid_o_t)-1:0]'(__valid_o);

  edge_propagator_rx i_edge_propagator_rx (
    .clk_i ( __clk_i ),
    .rstn_i ( __rstn_i ),
    .valid_i ( __valid_i ),
    .ack_o ( __ack_o ),
    .valid_o ( __valid_o )
  );

endmodule
