// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `exp_backoff` from `exp_backoff.sv`.
module exp_backoff_wrapper #(
  parameter int unsigned Seed   = 'hffff,

  parameter int unsigned MaxExp = 16
) (
  clk_i,
  rst_ni,
  set_i,
  clr_i,
  is_zero_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __set_i_t;
  typedef logic __clr_i_t;
  typedef logic __is_zero_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__set_i_t)-1:0] set_i;
  input logic [$bits(__clr_i_t)-1:0] clr_i;
  output logic [$bits(__is_zero_o_t)-1:0] is_zero_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __set_i_t __set_i;
  __clr_i_t __clr_i;
  __is_zero_o_t __is_zero_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __set_i = __set_i_t'(set_i);
  assign __clr_i = __clr_i_t'(clr_i);
  assign is_zero_o = logic [$bits(__is_zero_o_t)-1:0]'(__is_zero_o);

  exp_backoff #(
    .Seed ( Seed ),
    .MaxExp ( MaxExp )
  ) i_exp_backoff (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .set_i ( __set_i ),
    .clr_i ( __clr_i ),
    .is_zero_o ( __is_zero_o )
  );

endmodule
