// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `fall_through_register` from `fall_through_register.sv`.
module fall_through_register_wrapper #(
parameter type T = logic
) (
input  logic    clk_i,
    input  logic    rst_ni,
    input  logic    clr_i,
    input  logic    testmode_i,

    input  logic    valid_i,
    output logic    ready_o,
    input  T        data_i,

    output logic    valid_o,
    input  logic    ready_i,
    output T        data_o
);

  fall_through_register #(
    .T ( T )
  ) i_fall_through_register (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .clr_i ( clr_i ),
    .testmode_i ( testmode_i ),
    .valid_i ( valid_i ),
    .ready_o ( ready_o ),
    .data_i ( data_i ),
    .valid_o ( valid_o ),
    .ready_i ( ready_i ),
    .data_o ( data_o )
  );

endmodule
