// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `fifo_v3` from `fifo_v3.sv`.
module fifo_v3_wrapper #(
    parameter bit          FALL_THROUGH = 1'b0,
    parameter int unsigned DATA_WIDTH   = 32,
    parameter int unsigned DEPTH        = 8,
    parameter type dtype                = logic [DATA_WIDTH-1:0],

    parameter int unsigned ADDR_DEPTH   = (DEPTH > 1) ? $clog2(DEPTH) : 1
) (
  clk_i,
  rst_ni,
  flush_i,
  testmode_i,
  full_o,
  empty_o,
  usage_o,
  data_i,
  push_i,
  data_o,
  pop_i
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __flush_i_t;
  typedef logic __testmode_i_t;
  typedef logic __full_o_t;
  typedef logic __empty_o_t;
  typedef logic  [ADDR_DEPTH-1:0] __usage_o_t;
  typedef dtype __data_i_t;
  typedef logic __push_i_t;
  typedef dtype __data_o_t;
  typedef logic __pop_i_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__flush_i_t)-1:0] flush_i;
  input logic [$bits(__testmode_i_t)-1:0] testmode_i;
  output logic [$bits(__full_o_t)-1:0] full_o;
  output logic [$bits(__empty_o_t)-1:0] empty_o;
  output logic [$bits(__usage_o_t)-1:0] usage_o;
  input logic [$bits(__data_i_t)-1:0] data_i;
  input logic [$bits(__push_i_t)-1:0] push_i;
  output logic [$bits(__data_o_t)-1:0] data_o;
  input logic [$bits(__pop_i_t)-1:0] pop_i;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __flush_i_t __flush_i;
  __testmode_i_t __testmode_i;
  __full_o_t __full_o;
  __empty_o_t __empty_o;
  __usage_o_t __usage_o;
  __data_i_t __data_i;
  __push_i_t __push_i;
  __data_o_t __data_o;
  __pop_i_t __pop_i;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __flush_i = __flush_i_t'(flush_i);
  assign __testmode_i = __testmode_i_t'(testmode_i);
  assign full_o = logic [$bits(__full_o_t)-1:0]'(__full_o);
  assign empty_o = logic [$bits(__empty_o_t)-1:0]'(__empty_o);
  assign usage_o = logic [$bits(__usage_o_t)-1:0]'(__usage_o);
  assign __data_i = __data_i_t'(data_i);
  assign __push_i = __push_i_t'(push_i);
  assign data_o = logic [$bits(__data_o_t)-1:0]'(__data_o);
  assign __pop_i = __pop_i_t'(pop_i);

  fifo_v3 #(
    .FALL_THROUGH ( FALL_THROUGH ),
    .DATA_WIDTH ( DATA_WIDTH ),
    .DEPTH ( DEPTH ),
    .dtype ( dtype ),
    .ADDR_DEPTH ( ADDR_DEPTH )
  ) i_fifo_v3 (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .flush_i ( __flush_i ),
    .testmode_i ( __testmode_i ),
    .full_o ( __full_o ),
    .empty_o ( __empty_o ),
    .usage_o ( __usage_o ),
    .data_i ( __data_i ),
    .push_i ( __push_i ),
    .data_o ( __data_o ),
    .pop_i ( __pop_i )
  );

endmodule
