// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `fifo_v3` from `fifo_v3.sv`.
module fifo_v3_wrapper #(
parameter bit          FALL_THROUGH = 1'b0,
    parameter int unsigned DATA_WIDTH   = 32,
    parameter int unsigned DEPTH        = 8,
    parameter type dtype                = logic [DATA_WIDTH-1:0],

    parameter int unsigned ADDR_DEPTH   = (DEPTH > 1) ? $clog2(DEPTH) : 1
) (
input  logic  clk_i,
    input  logic  rst_ni,
    input  logic  flush_i,
    input  logic  testmode_i,

    output logic  full_o,
    output logic  empty_o,
    output logic  [ADDR_DEPTH-1:0] usage_o,

    input  dtype  data_i,
    input  logic  push_i,

    output dtype  data_o,
    input  logic  pop_i
);

  fifo_v3 #(
    .FALL_THROUGH ( FALL_THROUGH ),
    .DATA_WIDTH ( DATA_WIDTH ),
    .DEPTH ( DEPTH ),
    .dtype ( dtype ),
    .ADDR_DEPTH ( ADDR_DEPTH )
  ) i_fifo_v3 (
    .*
  );

endmodule
