// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `id_queue` from `id_queue.sv`.
module id_queue_wrapper #(
    parameter int ID_WIDTH  = 0,
    parameter int CAPACITY  = 0,
    parameter bit FULL_BW   = 0,
    parameter bit CUT_OUP_POP_INP_GNT = 0,
    parameter int NUM_CMP_PORTS = 1,
    parameter type data_t   = logic[31:0],

    localparam type id_t    = logic[ID_WIDTH-1:0]
) (
  clk_i,
  rst_ni,
  inp_id_i,
  inp_data_i,
  inp_req_i,
  inp_gnt_o,
  exists_data_i,
  exists_mask_i,
  exists_req_i,
  exists_o,
  exists_gnt_o,
  oup_id_i,
  oup_pop_i,
  oup_req_i,
  oup_data_o,
  oup_data_valid_o,
  oup_gnt_o,
  full_o,
  empty_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef id_t __inp_id_i_t;
  typedef data_t __inp_data_i_t;
  typedef logic __inp_req_i_t;
  typedef logic __inp_gnt_o_t;
  typedef data_t [NUM_CMP_PORTS-1:0] __exists_data_i_t;
  typedef data_t [NUM_CMP_PORTS-1:0] __exists_mask_i_t;
  typedef logic  [NUM_CMP_PORTS-1:0] __exists_req_i_t;
  typedef logic  [NUM_CMP_PORTS-1:0] __exists_o_t;
  typedef logic  [NUM_CMP_PORTS-1:0] __exists_gnt_o_t;
  typedef id_t __oup_id_i_t;
  typedef logic __oup_pop_i_t;
  typedef logic __oup_req_i_t;
  typedef data_t __oup_data_o_t;
  typedef logic __oup_data_valid_o_t;
  typedef logic __oup_gnt_o_t;
  typedef logic __full_o_t;
  typedef logic __empty_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__inp_id_i_t)-1:0] inp_id_i;
  input logic [$bits(__inp_data_i_t)-1:0] inp_data_i;
  input logic [$bits(__inp_req_i_t)-1:0] inp_req_i;
  output logic [$bits(__inp_gnt_o_t)-1:0] inp_gnt_o;
  input logic [$bits(__exists_data_i_t)-1:0] exists_data_i;
  input logic [$bits(__exists_mask_i_t)-1:0] exists_mask_i;
  input logic [$bits(__exists_req_i_t)-1:0] exists_req_i;
  output logic [$bits(__exists_o_t)-1:0] exists_o;
  output logic [$bits(__exists_gnt_o_t)-1:0] exists_gnt_o;
  input logic [$bits(__oup_id_i_t)-1:0] oup_id_i;
  input logic [$bits(__oup_pop_i_t)-1:0] oup_pop_i;
  input logic [$bits(__oup_req_i_t)-1:0] oup_req_i;
  output logic [$bits(__oup_data_o_t)-1:0] oup_data_o;
  output logic [$bits(__oup_data_valid_o_t)-1:0] oup_data_valid_o;
  output logic [$bits(__oup_gnt_o_t)-1:0] oup_gnt_o;
  output logic [$bits(__full_o_t)-1:0] full_o;
  output logic [$bits(__empty_o_t)-1:0] empty_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __inp_id_i_t __inp_id_i;
  __inp_data_i_t __inp_data_i;
  __inp_req_i_t __inp_req_i;
  __inp_gnt_o_t __inp_gnt_o;
  __exists_data_i_t __exists_data_i;
  __exists_mask_i_t __exists_mask_i;
  __exists_req_i_t __exists_req_i;
  __exists_o_t __exists_o;
  __exists_gnt_o_t __exists_gnt_o;
  __oup_id_i_t __oup_id_i;
  __oup_pop_i_t __oup_pop_i;
  __oup_req_i_t __oup_req_i;
  __oup_data_o_t __oup_data_o;
  __oup_data_valid_o_t __oup_data_valid_o;
  __oup_gnt_o_t __oup_gnt_o;
  __full_o_t __full_o;
  __empty_o_t __empty_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __inp_id_i = __inp_id_i_t'(inp_id_i);
  assign __inp_data_i = __inp_data_i_t'(inp_data_i);
  assign __inp_req_i = __inp_req_i_t'(inp_req_i);
  assign inp_gnt_o = logic [$bits(__inp_gnt_o_t)-1:0]'(__inp_gnt_o);
  assign __exists_data_i = __exists_data_i_t'(exists_data_i);
  assign __exists_mask_i = __exists_mask_i_t'(exists_mask_i);
  assign __exists_req_i = __exists_req_i_t'(exists_req_i);
  assign exists_o = logic [$bits(__exists_o_t)-1:0]'(__exists_o);
  assign exists_gnt_o = logic [$bits(__exists_gnt_o_t)-1:0]'(__exists_gnt_o);
  assign __oup_id_i = __oup_id_i_t'(oup_id_i);
  assign __oup_pop_i = __oup_pop_i_t'(oup_pop_i);
  assign __oup_req_i = __oup_req_i_t'(oup_req_i);
  assign oup_data_o = logic [$bits(__oup_data_o_t)-1:0]'(__oup_data_o);
  assign oup_data_valid_o = logic [$bits(__oup_data_valid_o_t)-1:0]'(__oup_data_valid_o);
  assign oup_gnt_o = logic [$bits(__oup_gnt_o_t)-1:0]'(__oup_gnt_o);
  assign full_o = logic [$bits(__full_o_t)-1:0]'(__full_o);
  assign empty_o = logic [$bits(__empty_o_t)-1:0]'(__empty_o);

  id_queue #(
    .ID_WIDTH ( ID_WIDTH ),
    .CAPACITY ( CAPACITY ),
    .FULL_BW ( FULL_BW ),
    .CUT_OUP_POP_INP_GNT ( CUT_OUP_POP_INP_GNT ),
    .NUM_CMP_PORTS ( NUM_CMP_PORTS ),
    .data_t ( data_t )
  ) i_id_queue (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .inp_id_i ( __inp_id_i ),
    .inp_data_i ( __inp_data_i ),
    .inp_req_i ( __inp_req_i ),
    .inp_gnt_o ( __inp_gnt_o ),
    .exists_data_i ( __exists_data_i ),
    .exists_mask_i ( __exists_mask_i ),
    .exists_req_i ( __exists_req_i ),
    .exists_o ( __exists_o ),
    .exists_gnt_o ( __exists_gnt_o ),
    .oup_id_i ( __oup_id_i ),
    .oup_pop_i ( __oup_pop_i ),
    .oup_req_i ( __oup_req_i ),
    .oup_data_o ( __oup_data_o ),
    .oup_data_valid_o ( __oup_data_valid_o ),
    .oup_gnt_o ( __oup_gnt_o ),
    .full_o ( __full_o ),
    .empty_o ( __empty_o )
  );

endmodule
