// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `id_queue` from `id_queue.sv`.
module id_queue_wrapper #(
parameter int ID_WIDTH  = 0,
  parameter int CAPACITY  = 0,
  parameter bit FULL_BW   = 0,
  parameter bit CUT_OUP_POP_INP_GNT = 0,
  parameter int NUM_CMP_PORTS = 1,
  parameter int unsigned data_t_WIDTH = 1,
  localparam type id_t    = logic[ID_WIDTH-1:0]
) (
input  logic    clk_i,
  input  logic    rst_ni,
  input  id_t     inp_id_i,
  input  logic [data_t_WIDTH-1:0]   inp_data_i,
  input  logic    inp_req_i,
  output logic    inp_gnt_o,
  input  logic [data_t_WIDTH-1:0] [NUM_CMP_PORTS-1:0] exists_data_i,
  input  logic [data_t_WIDTH-1:0] [NUM_CMP_PORTS-1:0] exists_mask_i,
  input  logic  [NUM_CMP_PORTS-1:0] exists_req_i,
  output logic  [NUM_CMP_PORTS-1:0] exists_o,
  output logic  [NUM_CMP_PORTS-1:0] exists_gnt_o,
  input  id_t     oup_id_i,
  input  logic    oup_pop_i,
  input  logic    oup_req_i,
  output logic [data_t_WIDTH-1:0]   oup_data_o,
  output logic    oup_data_valid_o,
  output logic    oup_gnt_o,
  output logic    full_o,
  output logic    empty_o
);

  id_queue #(
    .ID_WIDTH ( ID_WIDTH ),
    .CAPACITY ( CAPACITY ),
    .FULL_BW ( FULL_BW ),
    .CUT_OUP_POP_INP_GNT ( CUT_OUP_POP_INP_GNT ),
    .NUM_CMP_PORTS ( NUM_CMP_PORTS ),
    .data_t ( logic [data_t_WIDTH-1:0] )
  ) i_id_queue (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .inp_id_i ( inp_id_i ),
    .inp_data_i ( inp_data_i ),
    .inp_req_i ( inp_req_i ),
    .inp_gnt_o ( inp_gnt_o ),
    .exists_data_i ( exists_data_i ),
    .exists_mask_i ( exists_mask_i ),
    .exists_req_i ( exists_req_i ),
    .exists_o ( exists_o ),
    .exists_gnt_o ( exists_gnt_o ),
    .oup_id_i ( oup_id_i ),
    .oup_pop_i ( oup_pop_i ),
    .oup_req_i ( oup_req_i ),
    .oup_data_o ( oup_data_o ),
    .oup_data_valid_o ( oup_data_valid_o ),
    .oup_gnt_o ( oup_gnt_o ),
    .full_o ( full_o ),
    .empty_o ( empty_o )
  );

endmodule
