// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `isochronous_spill_register` from `isochronous_spill_register.sv`.
module isochronous_spill_register_wrapper #(
parameter type T      = logic,

  parameter bit  Bypass = 1'b0
) (
input  logic src_clk_i,

  input  logic src_rst_ni,

  input  logic src_valid_i,

  output logic src_ready_o,

  input  T     src_data_i,

  input  logic dst_clk_i,

  input  logic dst_rst_ni,

  output logic dst_valid_o,

  input  logic dst_ready_i,

  output T     dst_data_o
);

  isochronous_spill_register #(
    .T ( T ),
    .Bypass ( Bypass )
  ) i_isochronous_spill_register (
    .src_clk_i ( src_clk_i ),
    .src_rst_ni ( src_rst_ni ),
    .src_valid_i ( src_valid_i ),
    .src_ready_o ( src_ready_o ),
    .src_data_i ( src_data_i ),
    .dst_clk_i ( dst_clk_i ),
    .dst_rst_ni ( dst_rst_ni ),
    .dst_valid_o ( dst_valid_o ),
    .dst_ready_i ( dst_ready_i ),
    .dst_data_o ( dst_data_o )
  );

endmodule
