// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `lfsr` from `lfsr.sv`.
module lfsr_wrapper #(
parameter int unsigned          LfsrWidth     = 64,
  parameter int unsigned          OutWidth      = 8,
  parameter logic [LfsrWidth-1:0] RstVal        = '1,
  parameter int unsigned          CipherLayers  = 0,
  parameter bit                   CipherReg     = 1'b1
) (
input  logic                 clk_i,
  input  logic                 rst_ni,
  input  logic                 en_i,
  output logic [OutWidth-1:0]  out_o
);

  lfsr #(
    .LfsrWidth ( LfsrWidth ),
    .OutWidth ( OutWidth ),
    .RstVal ( RstVal ),
    .CipherLayers ( CipherLayers ),
    .CipherReg ( CipherReg )
  ) i_lfsr (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .en_i ( en_i ),
    .out_o ( out_o )
  );

endmodule
