// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `lfsr_16bit` from `lfsr_16bit.sv`.
module lfsr_16bit_wrapper #(
    parameter logic [15:0] SEED  = 8'b0,
    parameter int unsigned WIDTH = 16
) (
  clk_i,
  rst_ni,
  en_i,
  refill_way_oh,
  refill_way_bin
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __en_i_t;
  typedef logic [WIDTH-1:0] __refill_way_oh_t;
  typedef logic [$clog2(WIDTH)-1:0] __refill_way_bin_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__en_i_t)-1:0] en_i;
  output logic [$bits(__refill_way_oh_t)-1:0] refill_way_oh;
  output logic [$bits(__refill_way_bin_t)-1:0] refill_way_bin;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __en_i_t __en_i;
  __refill_way_oh_t __refill_way_oh;
  __refill_way_bin_t __refill_way_bin;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __en_i = __en_i_t'(en_i);
  assign refill_way_oh = logic [$bits(__refill_way_oh_t)-1:0]'(__refill_way_oh);
  assign refill_way_bin = logic [$bits(__refill_way_bin_t)-1:0]'(__refill_way_bin);

  lfsr_16bit #(
    .SEED ( SEED ),
    .WIDTH ( WIDTH )
  ) i_lfsr_16bit (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .en_i ( __en_i ),
    .refill_way_oh ( __refill_way_oh ),
    .refill_way_bin ( __refill_way_bin )
  );

endmodule
