// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `lfsr` from `lfsr.sv`.
module lfsr_wrapper #(
  parameter int unsigned          LfsrWidth     = 64,
  parameter int unsigned          OutWidth      = 8,
  parameter logic [LfsrWidth-1:0] RstVal        = '1,

  parameter int unsigned          CipherLayers  = 0,
  parameter bit                   CipherReg     = 1'b1
) (
  clk_i,
  rst_ni,
  en_i,
  out_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __en_i_t;
  typedef logic [OutWidth-1:0] __out_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__en_i_t)-1:0] en_i;
  output logic [$bits(__out_o_t)-1:0] out_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __en_i_t __en_i;
  __out_o_t __out_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __en_i = __en_i_t'(en_i);
  assign out_o = logic [$bits(__out_o_t)-1:0]'(__out_o);

  lfsr #(
    .LfsrWidth ( LfsrWidth ),
    .OutWidth ( OutWidth ),
    .RstVal ( RstVal ),
    .CipherLayers ( CipherLayers ),
    .CipherReg ( CipherReg )
  ) i_lfsr (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .en_i ( __en_i ),
    .out_o ( __out_o )
  );

endmodule
