// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `lossy_valid_to_stream` from `lossy_valid_to_stream.sv`.
module lossy_valid_to_stream_wrapper #(
parameter int unsigned DATA_WIDTH = 32,
    parameter type T = logic [DATA_WIDTH-1:0]
) (
input  logic clk_i,
    input  logic rst_ni,

    input  logic valid_i,
    input  T     data_i,

    output logic valid_o,
    input  logic ready_i,
    output T     data_o,

    output busy_o
);

  lossy_valid_to_stream #(
    .DATA_WIDTH ( DATA_WIDTH ),
    .T ( T )
  ) i_lossy_valid_to_stream (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .valid_i ( valid_i ),
    .data_i ( data_i ),
    .valid_o ( valid_o ),
    .ready_i ( ready_i ),
    .data_o ( data_o ),
    .busy_o ( busy_o )
  );

endmodule
