// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `lzc` from `lzc.sv`.
module lzc_wrapper #(
  parameter int unsigned WIDTH = 2,

  parameter bit          MODE  = 1'b0,

  parameter int unsigned CNT_WIDTH = cf_math_pkg::idx_width(WIDTH)
) (
  in_i,
  cnt_o,
  empty_o
);

  typedef logic [WIDTH-1:0] __in_i_t;
  typedef logic [CNT_WIDTH-1:0] __cnt_o_t;
  typedef logic __empty_o_t;

  input logic [$bits(__in_i_t)-1:0] in_i;
  output logic [$bits(__cnt_o_t)-1:0] cnt_o;
  output logic [$bits(__empty_o_t)-1:0] empty_o;

  __in_i_t __in_i;
  __cnt_o_t __cnt_o;
  __empty_o_t __empty_o;

  assign __in_i = __in_i_t'(in_i);
  assign cnt_o = logic [$bits(__cnt_o_t)-1:0]'(__cnt_o);
  assign empty_o = logic [$bits(__empty_o_t)-1:0]'(__empty_o);

  lzc #(
    .WIDTH ( WIDTH ),
    .MODE ( MODE ),
    .CNT_WIDTH ( CNT_WIDTH )
  ) i_lzc (
    .in_i ( __in_i ),
    .cnt_o ( __cnt_o ),
    .empty_o ( __empty_o )
  );

endmodule
