// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `mem_to_banks_detailed` from `mem_to_banks_detailed.sv`.
module mem_to_banks_detailed_wrapper #(
  parameter int unsigned AddrWidth = 32'd0,

  parameter int unsigned DataWidth = 32'd0,

  parameter int unsigned WUserWidth = 32'd0,

  parameter int unsigned RUserWidth = 32'd0,

  parameter int unsigned NumBanks  = 32'd1,

  parameter bit          HideStrb  = 1'b0,

  parameter int unsigned MaxTrans  = 32'd1,

  parameter int unsigned FifoDepth = 32'd1,

  parameter  type wuser_t     = logic [WUserWidth-1:0],

  localparam type addr_t      = logic [AddrWidth-1:0],

  localparam type inp_data_t  = logic [DataWidth-1:0],

  localparam type inp_strb_t  = logic [DataWidth/8-1:0],

  localparam type inp_ruser_t = logic [NumBanks-1:0][RUserWidth-1:0],

  localparam type oup_data_t  = logic [DataWidth/NumBanks-1:0],

  localparam type oup_strb_t  = logic [DataWidth/NumBanks/8-1:0],

  localparam type oup_ruser_t = logic [RUserWidth-1:0]
) (
  clk_i,
  rst_ni,
  req_i,
  gnt_o,
  addr_i,
  wdata_i,
  strb_i,
  wuser_i,
  we_i,
  rvalid_o,
  rdata_o,
  ruser_o,
  bank_req_o,
  bank_gnt_i,
  bank_addr_o,
  bank_wdata_o,
  bank_strb_o,
  bank_wuser_o,
  bank_we_o,
  bank_rvalid_i,
  bank_rdata_i,
  bank_ruser_i
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __req_i_t;
  typedef logic __gnt_o_t;
  typedef addr_t __addr_i_t;
  typedef inp_data_t __wdata_i_t;
  typedef inp_strb_t __strb_i_t;
  typedef wuser_t __wuser_i_t;
  typedef logic __we_i_t;
  typedef logic __rvalid_o_t;
  typedef inp_data_t __rdata_o_t;
  typedef inp_ruser_t __ruser_o_t;
  typedef logic       [NumBanks-1:0] __bank_req_o_t;
  typedef logic       [NumBanks-1:0] __bank_gnt_i_t;
  typedef addr_t      [NumBanks-1:0] __bank_addr_o_t;
  typedef oup_data_t  [NumBanks-1:0] __bank_wdata_o_t;
  typedef oup_strb_t  [NumBanks-1:0] __bank_strb_o_t;
  typedef wuser_t     [NumBanks-1:0] __bank_wuser_o_t;
  typedef logic       [NumBanks-1:0] __bank_we_o_t;
  typedef logic       [NumBanks-1:0] __bank_rvalid_i_t;
  typedef oup_data_t  [NumBanks-1:0] __bank_rdata_i_t;
  typedef oup_ruser_t [NumBanks-1:0] __bank_ruser_i_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__req_i_t)-1:0] req_i;
  output logic [$bits(__gnt_o_t)-1:0] gnt_o;
  input logic [$bits(__addr_i_t)-1:0] addr_i;
  input logic [$bits(__wdata_i_t)-1:0] wdata_i;
  input logic [$bits(__strb_i_t)-1:0] strb_i;
  input logic [$bits(__wuser_i_t)-1:0] wuser_i;
  input logic [$bits(__we_i_t)-1:0] we_i;
  output logic [$bits(__rvalid_o_t)-1:0] rvalid_o;
  output logic [$bits(__rdata_o_t)-1:0] rdata_o;
  output logic [$bits(__ruser_o_t)-1:0] ruser_o;
  output logic [$bits(__bank_req_o_t)-1:0] bank_req_o;
  input logic [$bits(__bank_gnt_i_t)-1:0] bank_gnt_i;
  output logic [$bits(__bank_addr_o_t)-1:0] bank_addr_o;
  output logic [$bits(__bank_wdata_o_t)-1:0] bank_wdata_o;
  output logic [$bits(__bank_strb_o_t)-1:0] bank_strb_o;
  output logic [$bits(__bank_wuser_o_t)-1:0] bank_wuser_o;
  output logic [$bits(__bank_we_o_t)-1:0] bank_we_o;
  input logic [$bits(__bank_rvalid_i_t)-1:0] bank_rvalid_i;
  input logic [$bits(__bank_rdata_i_t)-1:0] bank_rdata_i;
  input logic [$bits(__bank_ruser_i_t)-1:0] bank_ruser_i;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __req_i_t __req_i;
  __gnt_o_t __gnt_o;
  __addr_i_t __addr_i;
  __wdata_i_t __wdata_i;
  __strb_i_t __strb_i;
  __wuser_i_t __wuser_i;
  __we_i_t __we_i;
  __rvalid_o_t __rvalid_o;
  __rdata_o_t __rdata_o;
  __ruser_o_t __ruser_o;
  __bank_req_o_t __bank_req_o;
  __bank_gnt_i_t __bank_gnt_i;
  __bank_addr_o_t __bank_addr_o;
  __bank_wdata_o_t __bank_wdata_o;
  __bank_strb_o_t __bank_strb_o;
  __bank_wuser_o_t __bank_wuser_o;
  __bank_we_o_t __bank_we_o;
  __bank_rvalid_i_t __bank_rvalid_i;
  __bank_rdata_i_t __bank_rdata_i;
  __bank_ruser_i_t __bank_ruser_i;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __req_i = __req_i_t'(req_i);
  assign gnt_o = logic [$bits(__gnt_o_t)-1:0]'(__gnt_o);
  assign __addr_i = __addr_i_t'(addr_i);
  assign __wdata_i = __wdata_i_t'(wdata_i);
  assign __strb_i = __strb_i_t'(strb_i);
  assign __wuser_i = __wuser_i_t'(wuser_i);
  assign __we_i = __we_i_t'(we_i);
  assign rvalid_o = logic [$bits(__rvalid_o_t)-1:0]'(__rvalid_o);
  assign rdata_o = logic [$bits(__rdata_o_t)-1:0]'(__rdata_o);
  assign ruser_o = logic [$bits(__ruser_o_t)-1:0]'(__ruser_o);
  assign bank_req_o = logic [$bits(__bank_req_o_t)-1:0]'(__bank_req_o);
  assign __bank_gnt_i = __bank_gnt_i_t'(bank_gnt_i);
  assign bank_addr_o = logic [$bits(__bank_addr_o_t)-1:0]'(__bank_addr_o);
  assign bank_wdata_o = logic [$bits(__bank_wdata_o_t)-1:0]'(__bank_wdata_o);
  assign bank_strb_o = logic [$bits(__bank_strb_o_t)-1:0]'(__bank_strb_o);
  assign bank_wuser_o = logic [$bits(__bank_wuser_o_t)-1:0]'(__bank_wuser_o);
  assign bank_we_o = logic [$bits(__bank_we_o_t)-1:0]'(__bank_we_o);
  assign __bank_rvalid_i = __bank_rvalid_i_t'(bank_rvalid_i);
  assign __bank_rdata_i = __bank_rdata_i_t'(bank_rdata_i);
  assign __bank_ruser_i = __bank_ruser_i_t'(bank_ruser_i);

  mem_to_banks_detailed #(
    .AddrWidth ( AddrWidth ),
    .DataWidth ( DataWidth ),
    .WUserWidth ( WUserWidth ),
    .RUserWidth ( RUserWidth ),
    .NumBanks ( NumBanks ),
    .HideStrb ( HideStrb ),
    .MaxTrans ( MaxTrans ),
    .FifoDepth ( FifoDepth ),
    .wuser_t ( wuser_t )
  ) i_mem_to_banks_detailed (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .req_i ( __req_i ),
    .gnt_o ( __gnt_o ),
    .addr_i ( __addr_i ),
    .wdata_i ( __wdata_i ),
    .strb_i ( __strb_i ),
    .wuser_i ( __wuser_i ),
    .we_i ( __we_i ),
    .rvalid_o ( __rvalid_o ),
    .rdata_o ( __rdata_o ),
    .ruser_o ( __ruser_o ),
    .bank_req_o ( __bank_req_o ),
    .bank_gnt_i ( __bank_gnt_i ),
    .bank_addr_o ( __bank_addr_o ),
    .bank_wdata_o ( __bank_wdata_o ),
    .bank_strb_o ( __bank_strb_o ),
    .bank_wuser_o ( __bank_wuser_o ),
    .bank_we_o ( __bank_we_o ),
    .bank_rvalid_i ( __bank_rvalid_i ),
    .bank_rdata_i ( __bank_rdata_i ),
    .bank_ruser_i ( __bank_ruser_i )
  );

endmodule
