// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `mem_to_banks_detailed` from `mem_to_banks_detailed.sv`.
module mem_to_banks_detailed_wrapper #(
parameter int unsigned AddrWidth = 32'd0,

  parameter int unsigned DataWidth = 32'd0,

  parameter int unsigned WUserWidth = 32'd0,

  parameter int unsigned RUserWidth = 32'd0,

  parameter int unsigned NumBanks  = 32'd1,

  parameter bit          HideStrb  = 1'b0,

  parameter int unsigned MaxTrans  = 32'd1,

  parameter int unsigned FifoDepth = 32'd1,

  parameter  type wuser_t     = logic [WUserWidth-1:0],

  localparam type addr_t      = logic [AddrWidth-1:0],

  localparam type inp_data_t  = logic [DataWidth-1:0],

  localparam type inp_strb_t  = logic [DataWidth/8-1:0],

  localparam type inp_ruser_t = logic [NumBanks-1:0][RUserWidth-1:0],

  localparam type oup_data_t  = logic [DataWidth/NumBanks-1:0],

  localparam type oup_strb_t  = logic [DataWidth/NumBanks/8-1:0],

  localparam type oup_ruser_t = logic [RUserWidth-1:0]
) (
input  logic                       clk_i,

  input  logic                       rst_ni,

  input  logic                       req_i,

  output logic                       gnt_o,

  input  addr_t                      addr_i,

  input  inp_data_t                  wdata_i,

  input  inp_strb_t                  strb_i,

  input  wuser_t                     wuser_i,

  input  logic                       we_i,

  output logic                       rvalid_o,

  output inp_data_t                  rdata_o,

  output inp_ruser_t                 ruser_o,

  output logic       [NumBanks-1:0]  bank_req_o,

  input  logic       [NumBanks-1:0]  bank_gnt_i,

  output addr_t      [NumBanks-1:0]  bank_addr_o,

  output oup_data_t  [NumBanks-1:0]  bank_wdata_o,

  output oup_strb_t  [NumBanks-1:0]  bank_strb_o,

  output wuser_t     [NumBanks-1:0]  bank_wuser_o,

  output logic       [NumBanks-1:0]  bank_we_o,

  input  logic       [NumBanks-1:0]  bank_rvalid_i,

  input  oup_data_t  [NumBanks-1:0]  bank_rdata_i,

  input  oup_ruser_t [NumBanks-1:0]  bank_ruser_i
);

  mem_to_banks_detailed #(
    .AddrWidth ( AddrWidth ),
    .DataWidth ( DataWidth ),
    .WUserWidth ( WUserWidth ),
    .RUserWidth ( RUserWidth ),
    .NumBanks ( NumBanks ),
    .HideStrb ( HideStrb ),
    .MaxTrans ( MaxTrans ),
    .FifoDepth ( FifoDepth ),
    .wuser_t ( wuser_t )
  ) i_mem_to_banks_detailed (
    .*
  );

endmodule
