// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `multiaddr_decode` from `multiaddr_decode.sv`.
module multiaddr_decode_wrapper #(
  parameter int unsigned NoIndices = 32'd0,

  parameter int unsigned NoRules   = 32'd0,

  parameter type         addr_t    = logic,

  parameter type         rule_t    = logic
) (
  addr_i,
  mask_i,
  addr_map_i,
  select_o,
  addr_o,
  mask_o,
  dec_valid_o,
  dec_error_o
);

  typedef addr_t __addr_i_t;
  typedef addr_t __mask_i_t;
  typedef rule_t [NoRules-1:0] __addr_map_i_t;
  typedef logic  [NoIndices-1:0] __select_o_t;
  typedef addr_t [NoIndices-1:0] __addr_o_t;
  typedef addr_t [NoIndices-1:0] __mask_o_t;
  typedef logic __dec_valid_o_t;
  typedef logic __dec_error_o_t;

  input logic [$bits(__addr_i_t)-1:0] addr_i;
  input logic [$bits(__mask_i_t)-1:0] mask_i;
  input logic [$bits(__addr_map_i_t)-1:0] addr_map_i;
  output logic [$bits(__select_o_t)-1:0] select_o;
  output logic [$bits(__addr_o_t)-1:0] addr_o;
  output logic [$bits(__mask_o_t)-1:0] mask_o;
  output logic [$bits(__dec_valid_o_t)-1:0] dec_valid_o;
  output logic [$bits(__dec_error_o_t)-1:0] dec_error_o;

  __addr_i_t __addr_i;
  __mask_i_t __mask_i;
  __addr_map_i_t __addr_map_i;
  __select_o_t __select_o;
  __addr_o_t __addr_o;
  __mask_o_t __mask_o;
  __dec_valid_o_t __dec_valid_o;
  __dec_error_o_t __dec_error_o;

  assign __addr_i = __addr_i_t'(addr_i);
  assign __mask_i = __mask_i_t'(mask_i);
  assign __addr_map_i = __addr_map_i_t'(addr_map_i);
  assign select_o = logic [$bits(__select_o_t)-1:0]'(__select_o);
  assign addr_o = logic [$bits(__addr_o_t)-1:0]'(__addr_o);
  assign mask_o = logic [$bits(__mask_o_t)-1:0]'(__mask_o);
  assign dec_valid_o = logic [$bits(__dec_valid_o_t)-1:0]'(__dec_valid_o);
  assign dec_error_o = logic [$bits(__dec_error_o_t)-1:0]'(__dec_error_o);

  multiaddr_decode #(
    .NoIndices ( NoIndices ),
    .NoRules ( NoRules ),
    .addr_t ( addr_t ),
    .rule_t ( rule_t )
  ) i_multiaddr_decode (
    .addr_i ( __addr_i ),
    .mask_i ( __mask_i ),
    .addr_map_i ( __addr_map_i ),
    .select_o ( __select_o ),
    .addr_o ( __addr_o ),
    .mask_o ( __mask_o ),
    .dec_valid_o ( __dec_valid_o ),
    .dec_error_o ( __dec_error_o )
  );

endmodule
