// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `multiaddr_decode` from `multiaddr_decode.sv`.
module multiaddr_decode_wrapper #(
parameter int unsigned NoIndices = 32'd0,

  parameter int unsigned NoRules   = 32'd0,

  parameter type         addr_t    = logic,


























  parameter type         rule_t    = logic
) (
input  addr_t                 addr_i,
  input  addr_t                 mask_i,

  input  rule_t [NoRules-1:0]   addr_map_i,

  output logic  [NoIndices-1:0] select_o,

  output addr_t [NoIndices-1:0] addr_o,
  output addr_t [NoIndices-1:0] mask_o,

  output logic                  dec_valid_o,

  output logic                  dec_error_o
);

  multiaddr_decode #(
    .NoIndices ( NoIndices ),
    .NoRules ( NoRules ),
    .addr_t ( addr_t ),
    .rule_t ( rule_t )
  ) i_multiaddr_decode (
    .addr_i ( addr_i ),
    .mask_i ( mask_i ),
    .addr_map_i ( addr_map_i ),
    .select_o ( select_o ),
    .addr_o ( addr_o ),
    .mask_o ( mask_o ),
    .dec_valid_o ( dec_valid_o ),
    .dec_error_o ( dec_error_o )
  );

endmodule
