// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `mv_filter` from `mv_filter.sv`.
module mv_filter_wrapper #(
parameter int unsigned WIDTH     = 4,
    parameter int unsigned THRESHOLD = 10
) (
input  logic clk_i,
    input  logic rst_ni,
    input  logic sample_i,
    input  logic clear_i,
    input  logic d_i,
    output logic q_o
);

  mv_filter #(
    .WIDTH ( WIDTH ),
    .THRESHOLD ( THRESHOLD )
  ) i_mv_filter (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .sample_i ( sample_i ),
    .clear_i ( clear_i ),
    .d_i ( d_i ),
    .q_o ( q_o )
  );

endmodule
