// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `onehot_to_bin` from `onehot_to_bin.sv`.
module onehot_to_bin_wrapper #(
    parameter int unsigned ONEHOT_WIDTH = 16,

    parameter int unsigned BIN_WIDTH    = ONEHOT_WIDTH == 1 ? 1 : $clog2(ONEHOT_WIDTH)
) (
  onehot,
  bin
);

  typedef logic [ONEHOT_WIDTH-1:0] __onehot_t;
  typedef logic [BIN_WIDTH-1:0] __bin_t;

  input logic [$bits(__onehot_t)-1:0] onehot;
  output logic [$bits(__bin_t)-1:0] bin;

  __onehot_t __onehot;
  __bin_t __bin;

  assign __onehot = __onehot_t'(onehot);
  assign bin = logic [$bits(__bin_t)-1:0]'(__bin);

  onehot_to_bin #(
    .ONEHOT_WIDTH ( ONEHOT_WIDTH ),
    .BIN_WIDTH ( BIN_WIDTH )
  ) i_onehot_to_bin (
    .onehot ( __onehot ),
    .bin ( __bin )
  );

endmodule
