// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `passthrough_stream_fifo` from `passthrough_stream_fifo.sv`.
module passthrough_stream_fifo_wrapper #(
parameter int unsigned Depth       = 32'd8,

    parameter bit          PrintInfo   = 1'b0,

    parameter bit          SameCycleRW = 1'b1,

    parameter type         type_t      = logic
) (
input  logic                 clk_i,

    input  logic                 rst_ni,

    input  logic                 flush_i,

    input  logic                 testmode_i,

    input  type_t                data_i,

    input  logic                 valid_i,

    output logic                 ready_o,

    output type_t                data_o,

    output logic                 valid_o,

    input  logic                 ready_i
);

  passthrough_stream_fifo #(
    .Depth ( Depth ),
    .PrintInfo ( PrintInfo ),
    .SameCycleRW ( SameCycleRW ),
    .type_t ( type_t )
  ) i_passthrough_stream_fifo (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .flush_i ( flush_i ),
    .testmode_i ( testmode_i ),
    .data_i ( data_i ),
    .valid_i ( valid_i ),
    .ready_o ( ready_o ),
    .data_o ( data_o ),
    .valid_o ( valid_o ),
    .ready_i ( ready_i )
  );

endmodule
