// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `plru_tree` from `plru_tree.sv`.
module plru_tree_wrapper #(
  parameter int unsigned ENTRIES = 16
) (
  clk_i,
  rst_ni,
  used_i,
  plru_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic [ENTRIES-1:0] __used_i_t;
  typedef logic [ENTRIES-1:0] __plru_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__used_i_t)-1:0] used_i;
  output logic [$bits(__plru_o_t)-1:0] plru_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __used_i_t __used_i;
  __plru_o_t __plru_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __used_i = __used_i_t'(used_i);
  assign plru_o = logic [$bits(__plru_o_t)-1:0]'(__plru_o);

  plru_tree #(
    .ENTRIES ( ENTRIES )
  ) i_plru_tree (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .used_i ( __used_i ),
    .plru_o ( __plru_o )
  );

endmodule
