// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `plru_tree` from `plru_tree.sv`.
module plru_tree_wrapper #(
parameter int unsigned ENTRIES = 16
) (
input  logic               clk_i,
  input  logic               rst_ni,
  input  logic [ENTRIES-1:0] used_i,
  output logic [ENTRIES-1:0] plru_o
);

  plru_tree #(
    .ENTRIES ( ENTRIES )
  ) i_plru_tree (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .used_i ( used_i ),
    .plru_o ( plru_o )
  );

endmodule
