// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `popcount` from `popcount.sv`.
module popcount_wrapper #(
    parameter  int unsigned INPUT_WIDTH   = 256,
    localparam int unsigned PopcountWidth = $clog2(INPUT_WIDTH) + 1
) (
  data_i,
  popcount_o
);

  typedef logic [  INPUT_WIDTH-1:0] __data_i_t;
  typedef logic [PopcountWidth-1:0] __popcount_o_t;

  input logic [$bits(__data_i_t)-1:0] data_i;
  output logic [$bits(__popcount_o_t)-1:0] popcount_o;

  __data_i_t __data_i;
  __popcount_o_t __popcount_o;

  assign __data_i = __data_i_t'(data_i);
  assign popcount_o = logic [$bits(__popcount_o_t)-1:0]'(__popcount_o);

  popcount #(
    .INPUT_WIDTH ( INPUT_WIDTH )
  ) i_popcount (
    .data_i ( __data_i ),
    .popcount_o ( __popcount_o )
  );

endmodule
