// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `read` from `read.sv`.
module read_wrapper #(
parameter int unsigned Width = 1,
  parameter int unsigned T_WIDTH = 1
) (
input  logic [T_WIDTH-1:0] d_i,
  output logic [T_WIDTH-1:0] d_o
);

  read #(
    .Width ( Width ),
    .T ( logic [T_WIDTH-1:0] )
  ) i_read (
    .d_i ( d_i ),
    .d_o ( d_o )
  );

endmodule
