// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `read` from `read.sv`.
module read_wrapper #(
    parameter int unsigned Width = 1,
    parameter type T = logic [Width-1:0]
) (
  d_i,
  d_o
);

  typedef T __d_i_t;
  typedef T __d_o_t;

  input logic [$bits(__d_i_t)-1:0] d_i;
  output logic [$bits(__d_o_t)-1:0] d_o;

  __d_i_t __d_i;
  __d_o_t __d_o;

  assign __d_i = __d_i_t'(d_i);
  assign d_o = logic [$bits(__d_o_t)-1:0]'(__d_o);

  read #(
    .Width ( Width ),
    .T ( T )
  ) i_read (
    .d_i ( __d_i ),
    .d_o ( __d_o )
  );

endmodule
