// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `ring_buffer` from `ring_buffer.sv`.
module ring_buffer_wrapper #(
parameter int unsigned Depth = 32,
    parameter type data_t = logic,

    localparam int unsigned AddrWidth = cf_math_pkg::idx_width(Depth),
    localparam int unsigned StepWidth = cf_math_pkg::idx_width(Depth+1),
    localparam type addr_t = logic [AddrWidth-1:0],
    localparam type step_t = logic [StepWidth-1:0]
) (
input logic clk_i,
    input logic rst_ni,


    input logic wvalid_i,
    output logic wready_o,
    input data_t wdata_i,


    input logic rvalid_i,
    output logic rready_o,
    input addr_t raddr_i,
    output data_t rdata_o,



    input logic advance_i,
    input step_t step_i,


    output addr_t wptr_o,
    output addr_t rptr_o,
    output logic full_o,
    output logic empty_o
);

  ring_buffer #(
    .Depth ( Depth ),
    .data_t ( data_t )
  ) i_ring_buffer (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .wvalid_i ( wvalid_i ),
    .wready_o ( wready_o ),
    .wdata_i ( wdata_i ),
    .rvalid_i ( rvalid_i ),
    .rready_o ( rready_o ),
    .raddr_i ( raddr_i ),
    .rdata_o ( rdata_o ),
    .advance_i ( advance_i ),
    .step_i ( step_i ),
    .wptr_o ( wptr_o ),
    .rptr_o ( rptr_o ),
    .full_o ( full_o ),
    .empty_o ( empty_o )
  );

endmodule
