// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `ring_buffer` from `ring_buffer.sv`.
module ring_buffer_wrapper #(
    parameter int unsigned Depth = 32,
    parameter type data_t = logic,

    localparam int unsigned AddrWidth = cf_math_pkg::idx_width(Depth),
    localparam int unsigned StepWidth = cf_math_pkg::idx_width(Depth+1),
    localparam type addr_t = logic [AddrWidth-1:0],
    localparam type step_t = logic [StepWidth-1:0]
) (
  clk_i,
  rst_ni,
  wvalid_i,
  wready_o,
  wdata_i,
  rvalid_i,
  rready_o,
  raddr_i,
  rdata_o,
  advance_i,
  step_i,
  wptr_o,
  rptr_o,
  full_o,
  empty_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __wvalid_i_t;
  typedef logic __wready_o_t;
  typedef data_t __wdata_i_t;
  typedef logic __rvalid_i_t;
  typedef logic __rready_o_t;
  typedef addr_t __raddr_i_t;
  typedef data_t __rdata_o_t;
  typedef logic __advance_i_t;
  typedef step_t __step_i_t;
  typedef addr_t __wptr_o_t;
  typedef addr_t __rptr_o_t;
  typedef logic __full_o_t;
  typedef logic __empty_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__wvalid_i_t)-1:0] wvalid_i;
  output logic [$bits(__wready_o_t)-1:0] wready_o;
  input logic [$bits(__wdata_i_t)-1:0] wdata_i;
  input logic [$bits(__rvalid_i_t)-1:0] rvalid_i;
  output logic [$bits(__rready_o_t)-1:0] rready_o;
  input logic [$bits(__raddr_i_t)-1:0] raddr_i;
  output logic [$bits(__rdata_o_t)-1:0] rdata_o;
  input logic [$bits(__advance_i_t)-1:0] advance_i;
  input logic [$bits(__step_i_t)-1:0] step_i;
  output logic [$bits(__wptr_o_t)-1:0] wptr_o;
  output logic [$bits(__rptr_o_t)-1:0] rptr_o;
  output logic [$bits(__full_o_t)-1:0] full_o;
  output logic [$bits(__empty_o_t)-1:0] empty_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __wvalid_i_t __wvalid_i;
  __wready_o_t __wready_o;
  __wdata_i_t __wdata_i;
  __rvalid_i_t __rvalid_i;
  __rready_o_t __rready_o;
  __raddr_i_t __raddr_i;
  __rdata_o_t __rdata_o;
  __advance_i_t __advance_i;
  __step_i_t __step_i;
  __wptr_o_t __wptr_o;
  __rptr_o_t __rptr_o;
  __full_o_t __full_o;
  __empty_o_t __empty_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __wvalid_i = __wvalid_i_t'(wvalid_i);
  assign wready_o = logic [$bits(__wready_o_t)-1:0]'(__wready_o);
  assign __wdata_i = __wdata_i_t'(wdata_i);
  assign __rvalid_i = __rvalid_i_t'(rvalid_i);
  assign rready_o = logic [$bits(__rready_o_t)-1:0]'(__rready_o);
  assign __raddr_i = __raddr_i_t'(raddr_i);
  assign rdata_o = logic [$bits(__rdata_o_t)-1:0]'(__rdata_o);
  assign __advance_i = __advance_i_t'(advance_i);
  assign __step_i = __step_i_t'(step_i);
  assign wptr_o = logic [$bits(__wptr_o_t)-1:0]'(__wptr_o);
  assign rptr_o = logic [$bits(__rptr_o_t)-1:0]'(__rptr_o);
  assign full_o = logic [$bits(__full_o_t)-1:0]'(__full_o);
  assign empty_o = logic [$bits(__empty_o_t)-1:0]'(__empty_o);

  ring_buffer #(
    .Depth ( Depth ),
    .data_t ( data_t )
  ) i_ring_buffer (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .wvalid_i ( __wvalid_i ),
    .wready_o ( __wready_o ),
    .wdata_i ( __wdata_i ),
    .rvalid_i ( __rvalid_i ),
    .rready_o ( __rready_o ),
    .raddr_i ( __raddr_i ),
    .rdata_o ( __rdata_o ),
    .advance_i ( __advance_i ),
    .step_i ( __step_i ),
    .wptr_o ( __wptr_o ),
    .rptr_o ( __rptr_o ),
    .full_o ( __full_o ),
    .empty_o ( __empty_o )
  );

endmodule
