// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `rr_arb_tree` from `rr_arb_tree.sv`.
module rr_arb_tree_wrapper #(
parameter int unsigned NumIn      = 64,

  parameter int unsigned DataWidth  = 32,

  parameter type         DataType   = logic [DataWidth-1:0],






  parameter bit          ExtPrio    = 1'b0,






  parameter bit          AxiVldRdy  = 1'b0,






  parameter bit          LockIn     = 1'b0,



  parameter bit          FairArb    = 1'b1,


  parameter int unsigned IdxWidth   = (NumIn > 32'd1) ? unsigned'($clog2(NumIn)) : 32'd1,


  parameter type         idx_t      = logic [IdxWidth-1:0]
) (
input  logic                clk_i,

  input  logic                rst_ni,

  input  logic                flush_i,

  input  idx_t                rr_i,

  input  logic    [NumIn-1:0] req_i,


  output logic    [NumIn-1:0] gnt_o,


  input  DataType [NumIn-1:0] data_i,

  output logic                req_o,

  input  logic                gnt_i,

  output DataType             data_o,

  output idx_t                idx_o
);

  rr_arb_tree #(
    .NumIn ( NumIn ),
    .DataWidth ( DataWidth ),
    .DataType ( DataType ),
    .ExtPrio ( ExtPrio ),
    .AxiVldRdy ( AxiVldRdy ),
    .LockIn ( LockIn ),
    .FairArb ( FairArb ),
    .IdxWidth ( IdxWidth ),
    .idx_t ( idx_t )
  ) i_rr_arb_tree (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .flush_i ( flush_i ),
    .rr_i ( rr_i ),
    .req_i ( req_i ),
    .gnt_o ( gnt_o ),
    .data_i ( data_i ),
    .req_o ( req_o ),
    .gnt_i ( gnt_i ),
    .data_o ( data_o ),
    .idx_o ( idx_o )
  );

endmodule
