// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `rr_arb_tree` from `rr_arb_tree.sv`.
module rr_arb_tree_wrapper #(
  parameter int unsigned NumIn      = 64,

  parameter int unsigned DataWidth  = 32,

  parameter type         DataType   = logic [DataWidth-1:0],

  parameter bit          ExtPrio    = 1'b0,

  parameter bit          AxiVldRdy  = 1'b0,

  parameter bit          LockIn     = 1'b0,

  parameter bit          FairArb    = 1'b1,

  parameter int unsigned IdxWidth   = (NumIn > 32'd1) ? unsigned'($clog2(NumIn)) : 32'd1,

  parameter type         idx_t      = logic [IdxWidth-1:0]
) (
  clk_i,
  rst_ni,
  flush_i,
  rr_i,
  req_i,
  gnt_o,
  data_i,
  req_o,
  gnt_i,
  data_o,
  idx_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __flush_i_t;
  typedef idx_t __rr_i_t;
  typedef logic    [NumIn-1:0] __req_i_t;
  typedef logic    [NumIn-1:0] __gnt_o_t;
  typedef DataType [NumIn-1:0] __data_i_t;
  typedef logic __req_o_t;
  typedef logic __gnt_i_t;
  typedef DataType __data_o_t;
  typedef idx_t __idx_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__flush_i_t)-1:0] flush_i;
  input logic [$bits(__rr_i_t)-1:0] rr_i;
  input logic [$bits(__req_i_t)-1:0] req_i;
  output logic [$bits(__gnt_o_t)-1:0] gnt_o;
  input logic [$bits(__data_i_t)-1:0] data_i;
  output logic [$bits(__req_o_t)-1:0] req_o;
  input logic [$bits(__gnt_i_t)-1:0] gnt_i;
  output logic [$bits(__data_o_t)-1:0] data_o;
  output logic [$bits(__idx_o_t)-1:0] idx_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __flush_i_t __flush_i;
  __rr_i_t __rr_i;
  __req_i_t __req_i;
  __gnt_o_t __gnt_o;
  __data_i_t __data_i;
  __req_o_t __req_o;
  __gnt_i_t __gnt_i;
  __data_o_t __data_o;
  __idx_o_t __idx_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __flush_i = __flush_i_t'(flush_i);
  assign __rr_i = __rr_i_t'(rr_i);
  assign __req_i = __req_i_t'(req_i);
  assign gnt_o = logic [$bits(__gnt_o_t)-1:0]'(__gnt_o);
  assign __data_i = __data_i_t'(data_i);
  assign req_o = logic [$bits(__req_o_t)-1:0]'(__req_o);
  assign __gnt_i = __gnt_i_t'(gnt_i);
  assign data_o = logic [$bits(__data_o_t)-1:0]'(__data_o);
  assign idx_o = logic [$bits(__idx_o_t)-1:0]'(__idx_o);

  rr_arb_tree #(
    .NumIn ( NumIn ),
    .DataWidth ( DataWidth ),
    .DataType ( DataType ),
    .ExtPrio ( ExtPrio ),
    .AxiVldRdy ( AxiVldRdy ),
    .LockIn ( LockIn ),
    .FairArb ( FairArb ),
    .IdxWidth ( IdxWidth ),
    .idx_t ( idx_t )
  ) i_rr_arb_tree (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .flush_i ( __flush_i ),
    .rr_i ( __rr_i ),
    .req_i ( __req_i ),
    .gnt_o ( __gnt_o ),
    .data_i ( __data_i ),
    .req_o ( __req_o ),
    .gnt_i ( __gnt_i ),
    .data_o ( __data_o ),
    .idx_o ( __idx_o )
  );

endmodule
