// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `rstgen` from `rstgen.sv`.
module rstgen_wrapper (
  clk_i,
  rst_ni,
  test_mode_i,
  rst_no,
  init_no
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __test_mode_i_t;
  typedef logic __rst_no_t;
  typedef logic __init_no_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__test_mode_i_t)-1:0] test_mode_i;
  output logic [$bits(__rst_no_t)-1:0] rst_no;
  output logic [$bits(__init_no_t)-1:0] init_no;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __test_mode_i_t __test_mode_i;
  __rst_no_t __rst_no;
  __init_no_t __init_no;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __test_mode_i = __test_mode_i_t'(test_mode_i);
  assign rst_no = logic [$bits(__rst_no_t)-1:0]'(__rst_no);
  assign init_no = logic [$bits(__init_no_t)-1:0]'(__init_no);

  rstgen i_rstgen (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .test_mode_i ( __test_mode_i ),
    .rst_no ( __rst_no ),
    .init_no ( __init_no )
  );

endmodule
