// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `serial_deglitch` from `serial_deglitch.sv`.
module serial_deglitch_wrapper #(
    parameter int unsigned SIZE = 4
) (
  clk_i,
  rst_ni,
  en_i,
  d_i,
  q_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __en_i_t;
  typedef logic __d_i_t;
  typedef logic __q_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__en_i_t)-1:0] en_i;
  input logic [$bits(__d_i_t)-1:0] d_i;
  output logic [$bits(__q_o_t)-1:0] q_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __en_i_t __en_i;
  __d_i_t __d_i;
  __q_o_t __q_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __en_i = __en_i_t'(en_i);
  assign __d_i = __d_i_t'(d_i);
  assign q_o = logic [$bits(__q_o_t)-1:0]'(__q_o);

  serial_deglitch #(
    .SIZE ( SIZE )
  ) i_serial_deglitch (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .en_i ( __en_i ),
    .d_i ( __d_i ),
    .q_o ( __q_o )
  );

endmodule
