// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `serial_deglitch` from `serial_deglitch.sv`.
module serial_deglitch_wrapper #(
parameter int unsigned SIZE = 4
) (
input  logic clk_i,
    input  logic rst_ni,
    input  logic en_i,
    input  logic d_i,
    output logic q_o
);

  serial_deglitch #(
    .SIZE ( SIZE )
  ) i_serial_deglitch (
    .*
  );

endmodule
