// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `shift_reg` from `shift_reg.sv`.
module shift_reg_wrapper #(
parameter type dtype         = logic,
    parameter int unsigned Depth = 1
) (
input  logic clk_i,
    input  logic rst_ni,
    input  dtype d_i,
    output dtype d_o
);

  shift_reg #(
    .dtype ( dtype ),
    .Depth ( Depth )
  ) i_shift_reg (
    .*
  );

endmodule
