// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `shift_reg_gated` from `shift_reg_gated.sv`.
module shift_reg_gated_wrapper #(
parameter int unsigned Depth = 32'd8,
  parameter int unsigned dtype_WIDTH = 1
) (
input  logic clk_i,
  input  logic rst_ni,
  input  logic valid_i,
  input  logic [dtype_WIDTH-1:0] data_i,
  output logic valid_o,
  output logic [dtype_WIDTH-1:0] data_o
);

  shift_reg_gated #(
    .Depth ( Depth ),
    .dtype ( logic [dtype_WIDTH-1:0] )
  ) i_shift_reg_gated (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .valid_i ( valid_i ),
    .data_i ( data_i ),
    .valid_o ( valid_o ),
    .data_o ( data_o )
  );

endmodule
