// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `shift_reg` from `shift_reg.sv`.
module shift_reg_wrapper #(
    parameter type dtype         = logic,
    parameter int unsigned Depth = 1
) (
  clk_i,
  rst_ni,
  d_i,
  d_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef dtype __d_i_t;
  typedef dtype __d_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__d_i_t)-1:0] d_i;
  output logic [$bits(__d_o_t)-1:0] d_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __d_i_t __d_i;
  __d_o_t __d_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __d_i = __d_i_t'(d_i);
  assign d_o = logic [$bits(__d_o_t)-1:0]'(__d_o);

  shift_reg #(
    .dtype ( dtype ),
    .Depth ( Depth )
  ) i_shift_reg (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .d_i ( __d_i ),
    .d_o ( __d_o )
  );

endmodule
