// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `shift_reg_gated` from `shift_reg_gated.sv`.
module shift_reg_gated_wrapper #(
  parameter int unsigned Depth = 32'd8,
  parameter type         dtype = logic
) (
  clk_i,
  rst_ni,
  valid_i,
  data_i,
  valid_o,
  data_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __valid_i_t;
  typedef dtype __data_i_t;
  typedef logic __valid_o_t;
  typedef dtype __data_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__valid_i_t)-1:0] valid_i;
  input logic [$bits(__data_i_t)-1:0] data_i;
  output logic [$bits(__valid_o_t)-1:0] valid_o;
  output logic [$bits(__data_o_t)-1:0] data_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __valid_i_t __valid_i;
  __data_i_t __data_i;
  __valid_o_t __valid_o;
  __data_o_t __data_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __valid_i = __valid_i_t'(valid_i);
  assign __data_i = __data_i_t'(data_i);
  assign valid_o = logic [$bits(__valid_o_t)-1:0]'(__valid_o);
  assign data_o = logic [$bits(__data_o_t)-1:0]'(__data_o);

  shift_reg_gated #(
    .Depth ( Depth ),
    .dtype ( dtype )
  ) i_shift_reg_gated (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .valid_i ( __valid_i ),
    .data_i ( __data_i ),
    .valid_o ( __valid_o ),
    .data_o ( __data_o )
  );

endmodule
