// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `stream_delay` from `stream_delay.sv`.
module stream_delay_wrapper #(
    parameter bit   StallRandom = 0,
    parameter int   FixedDelay  = 1,
    parameter type  payload_t  = logic,
    parameter logic [15:0] Seed = '0
) (
  clk_i,
  rst_ni,
  payload_i,
  ready_o,
  valid_i,
  payload_o,
  ready_i,
  valid_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef payload_t __payload_i_t;
  typedef logic __ready_o_t;
  typedef logic __valid_i_t;
  typedef payload_t __payload_o_t;
  typedef logic __ready_i_t;
  typedef logic __valid_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__payload_i_t)-1:0] payload_i;
  output logic [$bits(__ready_o_t)-1:0] ready_o;
  input logic [$bits(__valid_i_t)-1:0] valid_i;
  output logic [$bits(__payload_o_t)-1:0] payload_o;
  input logic [$bits(__ready_i_t)-1:0] ready_i;
  output logic [$bits(__valid_o_t)-1:0] valid_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __payload_i_t __payload_i;
  __ready_o_t __ready_o;
  __valid_i_t __valid_i;
  __payload_o_t __payload_o;
  __ready_i_t __ready_i;
  __valid_o_t __valid_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __payload_i = __payload_i_t'(payload_i);
  assign ready_o = logic [$bits(__ready_o_t)-1:0]'(__ready_o);
  assign __valid_i = __valid_i_t'(valid_i);
  assign payload_o = logic [$bits(__payload_o_t)-1:0]'(__payload_o);
  assign __ready_i = __ready_i_t'(ready_i);
  assign valid_o = logic [$bits(__valid_o_t)-1:0]'(__valid_o);

  stream_delay #(
    .StallRandom ( StallRandom ),
    .FixedDelay ( FixedDelay ),
    .payload_t ( payload_t ),
    .Seed ( Seed )
  ) i_stream_delay (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .payload_i ( __payload_i ),
    .ready_o ( __ready_o ),
    .valid_i ( __valid_i ),
    .payload_o ( __payload_o ),
    .ready_i ( __ready_i ),
    .valid_o ( __valid_o )
  );

endmodule
