// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `stream_fifo_optimal_wrap` from `stream_fifo_optimal_wrap.sv`.
module stream_fifo_optimal_wrap_wrapper #(
    parameter int unsigned Depth = 32'd8,

    parameter type type_t = logic,

    parameter bit PrintInfo = 1'b0,

    parameter int unsigned AddrDepth  = (Depth > 32'd1) ? $clog2(Depth) : 32'd1
) (
  clk_i,
  rst_ni,
  flush_i,
  testmode_i,
  usage_o,
  data_i,
  valid_i,
  ready_o,
  data_o,
  valid_o,
  ready_i
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __flush_i_t;
  typedef logic __testmode_i_t;
  typedef logic [AddrDepth-1:0] __usage_o_t;
  typedef type_t __data_i_t;
  typedef logic __valid_i_t;
  typedef logic __ready_o_t;
  typedef type_t __data_o_t;
  typedef logic __valid_o_t;
  typedef logic __ready_i_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__flush_i_t)-1:0] flush_i;
  input logic [$bits(__testmode_i_t)-1:0] testmode_i;
  output logic [$bits(__usage_o_t)-1:0] usage_o;
  input logic [$bits(__data_i_t)-1:0] data_i;
  input logic [$bits(__valid_i_t)-1:0] valid_i;
  output logic [$bits(__ready_o_t)-1:0] ready_o;
  output logic [$bits(__data_o_t)-1:0] data_o;
  output logic [$bits(__valid_o_t)-1:0] valid_o;
  input logic [$bits(__ready_i_t)-1:0] ready_i;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __flush_i_t __flush_i;
  __testmode_i_t __testmode_i;
  __usage_o_t __usage_o;
  __data_i_t __data_i;
  __valid_i_t __valid_i;
  __ready_o_t __ready_o;
  __data_o_t __data_o;
  __valid_o_t __valid_o;
  __ready_i_t __ready_i;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __flush_i = __flush_i_t'(flush_i);
  assign __testmode_i = __testmode_i_t'(testmode_i);
  assign usage_o = logic [$bits(__usage_o_t)-1:0]'(__usage_o);
  assign __data_i = __data_i_t'(data_i);
  assign __valid_i = __valid_i_t'(valid_i);
  assign ready_o = logic [$bits(__ready_o_t)-1:0]'(__ready_o);
  assign data_o = logic [$bits(__data_o_t)-1:0]'(__data_o);
  assign valid_o = logic [$bits(__valid_o_t)-1:0]'(__valid_o);
  assign __ready_i = __ready_i_t'(ready_i);

  stream_fifo_optimal_wrap #(
    .Depth ( Depth ),
    .type_t ( type_t ),
    .PrintInfo ( PrintInfo ),
    .AddrDepth ( AddrDepth )
  ) i_stream_fifo_optimal_wrap (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .flush_i ( __flush_i ),
    .testmode_i ( __testmode_i ),
    .usage_o ( __usage_o ),
    .data_i ( __data_i ),
    .valid_i ( __valid_i ),
    .ready_o ( __ready_o ),
    .data_o ( __data_o ),
    .valid_o ( __valid_o ),
    .ready_i ( __ready_i )
  );

endmodule
