// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `stream_register` from `stream_register.sv`.
module stream_register_wrapper #(
    parameter type T = logic
) (
  clk_i,
  rst_ni,
  clr_i,
  testmode_i,
  valid_i,
  ready_o,
  data_i,
  valid_o,
  ready_i,
  data_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __clr_i_t;
  typedef logic __testmode_i_t;
  typedef logic __valid_i_t;
  typedef logic __ready_o_t;
  typedef T __data_i_t;
  typedef logic __valid_o_t;
  typedef logic __ready_i_t;
  typedef T __data_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__clr_i_t)-1:0] clr_i;
  input logic [$bits(__testmode_i_t)-1:0] testmode_i;
  input logic [$bits(__valid_i_t)-1:0] valid_i;
  output logic [$bits(__ready_o_t)-1:0] ready_o;
  input logic [$bits(__data_i_t)-1:0] data_i;
  output logic [$bits(__valid_o_t)-1:0] valid_o;
  input logic [$bits(__ready_i_t)-1:0] ready_i;
  output logic [$bits(__data_o_t)-1:0] data_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __clr_i_t __clr_i;
  __testmode_i_t __testmode_i;
  __valid_i_t __valid_i;
  __ready_o_t __ready_o;
  __data_i_t __data_i;
  __valid_o_t __valid_o;
  __ready_i_t __ready_i;
  __data_o_t __data_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __clr_i = __clr_i_t'(clr_i);
  assign __testmode_i = __testmode_i_t'(testmode_i);
  assign __valid_i = __valid_i_t'(valid_i);
  assign ready_o = logic [$bits(__ready_o_t)-1:0]'(__ready_o);
  assign __data_i = __data_i_t'(data_i);
  assign valid_o = logic [$bits(__valid_o_t)-1:0]'(__valid_o);
  assign __ready_i = __ready_i_t'(ready_i);
  assign data_o = logic [$bits(__data_o_t)-1:0]'(__data_o);

  stream_register #(
    .T ( T )
  ) i_stream_register (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .clr_i ( __clr_i ),
    .testmode_i ( __testmode_i ),
    .valid_i ( __valid_i ),
    .ready_o ( __ready_o ),
    .data_i ( __data_i ),
    .valid_o ( __valid_o ),
    .ready_i ( __ready_i ),
    .data_o ( __data_o )
  );

endmodule
