// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `stream_fork_dynamic` from `stream_fork_dynamic.sv`.
module stream_fork_dynamic_wrapper #(
  parameter int unsigned N_OUP = 32'd0
) (
  clk_i,
  rst_ni,
  valid_i,
  ready_o,
  sel_i,
  sel_valid_i,
  sel_ready_o,
  valid_o,
  ready_i
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __valid_i_t;
  typedef logic __ready_o_t;
  typedef logic [N_OUP-1:0] __sel_i_t;
  typedef logic __sel_valid_i_t;
  typedef logic __sel_ready_o_t;
  typedef logic [N_OUP-1:0] __valid_o_t;
  typedef logic [N_OUP-1:0] __ready_i_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__valid_i_t)-1:0] valid_i;
  output logic [$bits(__ready_o_t)-1:0] ready_o;
  input logic [$bits(__sel_i_t)-1:0] sel_i;
  input logic [$bits(__sel_valid_i_t)-1:0] sel_valid_i;
  output logic [$bits(__sel_ready_o_t)-1:0] sel_ready_o;
  output logic [$bits(__valid_o_t)-1:0] valid_o;
  input logic [$bits(__ready_i_t)-1:0] ready_i;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __valid_i_t __valid_i;
  __ready_o_t __ready_o;
  __sel_i_t __sel_i;
  __sel_valid_i_t __sel_valid_i;
  __sel_ready_o_t __sel_ready_o;
  __valid_o_t __valid_o;
  __ready_i_t __ready_i;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __valid_i = __valid_i_t'(valid_i);
  assign ready_o = logic [$bits(__ready_o_t)-1:0]'(__ready_o);
  assign __sel_i = __sel_i_t'(sel_i);
  assign __sel_valid_i = __sel_valid_i_t'(sel_valid_i);
  assign sel_ready_o = logic [$bits(__sel_ready_o_t)-1:0]'(__sel_ready_o);
  assign valid_o = logic [$bits(__valid_o_t)-1:0]'(__valid_o);
  assign __ready_i = __ready_i_t'(ready_i);

  stream_fork_dynamic #(
    .N_OUP ( N_OUP )
  ) i_stream_fork_dynamic (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .valid_i ( __valid_i ),
    .ready_o ( __ready_o ),
    .sel_i ( __sel_i ),
    .sel_valid_i ( __sel_valid_i ),
    .sel_ready_o ( __sel_ready_o ),
    .valid_o ( __valid_o ),
    .ready_i ( __ready_i )
  );

endmodule
