// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `stream_register` from `stream_register.sv`.
module stream_register_wrapper #(
parameter int unsigned T_WIDTH = 1
) (
input  logic    clk_i,
  input  logic    rst_ni,
  input  logic    clr_i,
  input  logic    testmode_i,
  input  logic    valid_i,
  output logic    ready_o,
  input  logic [T_WIDTH-1:0]        data_i,
  output logic    valid_o,
  input  logic    ready_i,
  output logic [T_WIDTH-1:0]        data_o
);

  stream_register #(
    .T ( logic [T_WIDTH-1:0] )
  ) i_stream_register (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .clr_i ( clr_i ),
    .testmode_i ( testmode_i ),
    .valid_i ( valid_i ),
    .ready_o ( ready_o ),
    .data_i ( data_i ),
    .valid_o ( valid_o ),
    .ready_i ( ready_i ),
    .data_o ( data_o )
  );

endmodule
