// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `stream_delay` from `stream_delay.sv`.
module stream_delay_wrapper #(
parameter bit   StallRandom = 0,
    parameter int   FixedDelay  = 1,
    parameter type  payload_t  = logic,
    parameter logic [15:0] Seed = '0
) (
input  logic     clk_i,
    input  logic     rst_ni,

    input  payload_t payload_i,
    output logic     ready_o,
    input  logic     valid_i,

    output payload_t payload_o,
    input  logic     ready_i,
    output logic     valid_o
);

  stream_delay #(
    .StallRandom ( StallRandom ),
    .FixedDelay ( FixedDelay ),
    .payload_t ( payload_t ),
    .Seed ( Seed )
  ) i_stream_delay (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .payload_i ( payload_i ),
    .ready_o ( ready_o ),
    .valid_i ( valid_i ),
    .payload_o ( payload_o ),
    .ready_i ( ready_i ),
    .valid_o ( valid_o )
  );

endmodule
