// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `stream_mux` from `stream_mux.sv`.
module stream_mux_wrapper #(
  parameter type DATA_T = logic,
  parameter integer N_INP = 0,

  parameter integer SEL_WIDTH = cf_math_pkg::idx_width(N_INP)
) (
  inp_data_i,
  inp_valid_i,
  inp_ready_o,
  inp_sel_i,
  oup_data_o,
  oup_valid_o,
  oup_ready_i
);

  typedef DATA_T [N_INP-1:0] __inp_data_i_t;
  typedef logic  [N_INP-1:0] __inp_valid_i_t;
  typedef logic  [N_INP-1:0] __inp_ready_o_t;
  typedef logic  [SEL_WIDTH-1:0] __inp_sel_i_t;
  typedef DATA_T __oup_data_o_t;
  typedef logic __oup_valid_o_t;
  typedef logic __oup_ready_i_t;

  input logic [$bits(__inp_data_i_t)-1:0] inp_data_i;
  input logic [$bits(__inp_valid_i_t)-1:0] inp_valid_i;
  output logic [$bits(__inp_ready_o_t)-1:0] inp_ready_o;
  input logic [$bits(__inp_sel_i_t)-1:0] inp_sel_i;
  output logic [$bits(__oup_data_o_t)-1:0] oup_data_o;
  output logic [$bits(__oup_valid_o_t)-1:0] oup_valid_o;
  input logic [$bits(__oup_ready_i_t)-1:0] oup_ready_i;

  __inp_data_i_t __inp_data_i;
  __inp_valid_i_t __inp_valid_i;
  __inp_ready_o_t __inp_ready_o;
  __inp_sel_i_t __inp_sel_i;
  __oup_data_o_t __oup_data_o;
  __oup_valid_o_t __oup_valid_o;
  __oup_ready_i_t __oup_ready_i;

  assign __inp_data_i = __inp_data_i_t'(inp_data_i);
  assign __inp_valid_i = __inp_valid_i_t'(inp_valid_i);
  assign inp_ready_o = logic [$bits(__inp_ready_o_t)-1:0]'(__inp_ready_o);
  assign __inp_sel_i = __inp_sel_i_t'(inp_sel_i);
  assign oup_data_o = logic [$bits(__oup_data_o_t)-1:0]'(__oup_data_o);
  assign oup_valid_o = logic [$bits(__oup_valid_o_t)-1:0]'(__oup_valid_o);
  assign __oup_ready_i = __oup_ready_i_t'(oup_ready_i);

  stream_mux #(
    .DATA_T ( DATA_T ),
    .N_INP ( N_INP ),
    .SEL_WIDTH ( SEL_WIDTH )
  ) i_stream_mux (
    .inp_data_i ( __inp_data_i ),
    .inp_valid_i ( __inp_valid_i ),
    .inp_ready_o ( __inp_ready_o ),
    .inp_sel_i ( __inp_sel_i ),
    .oup_data_o ( __oup_data_o ),
    .oup_valid_o ( __oup_valid_o ),
    .oup_ready_i ( __oup_ready_i )
  );

endmodule
