// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `stream_omega_net` from `stream_omega_net.sv`.
module stream_omega_net_wrapper #(
parameter int unsigned NumInp      = 32'd0,

  parameter int unsigned NumOut      = 32'd0,


  parameter int unsigned Radix       = 32'd2,

  parameter int unsigned DataWidth   = 32'd1,

  parameter type         payload_t   = logic [DataWidth-1:0],

  parameter bit          SpillReg = 1'b0,

  parameter int unsigned ExtPrio     = 1'b0,


  parameter int unsigned AxiVldRdy   = 1'b1,



  parameter int unsigned LockIn      = 1'b1,



  parameter payload_t    AxiVldMask  = '1,



  parameter int unsigned SelWidth = (NumOut > 32'd1) ? unsigned'($clog2(NumOut)) : 32'd1,



  parameter type sel_oup_t = logic[SelWidth-1:0],



  parameter int unsigned IdxWidth = (NumInp > 32'd1) ? unsigned'($clog2(NumInp)) : 32'd1,



  parameter type idx_inp_t = logic[IdxWidth-1:0]
) (
input  logic                  clk_i,

  input  logic                  rst_ni,




  input  logic                  flush_i,


  input  idx_inp_t [NumOut-1:0] rr_i,


  input  payload_t [NumInp-1:0] data_i,


  input  sel_oup_t [NumInp-1:0] sel_i,

  input  logic     [NumInp-1:0] valid_i,

  output logic     [NumInp-1:0] ready_o,

  output payload_t [NumOut-1:0] data_o,

  output idx_inp_t [NumOut-1:0] idx_o,

  output logic     [NumOut-1:0] valid_o,

  input  logic     [NumOut-1:0] ready_i
);

  stream_omega_net #(
    .NumInp ( NumInp ),
    .NumOut ( NumOut ),
    .Radix ( Radix ),
    .DataWidth ( DataWidth ),
    .payload_t ( payload_t ),
    .SpillReg ( SpillReg ),
    .ExtPrio ( ExtPrio ),
    .AxiVldRdy ( AxiVldRdy ),
    .LockIn ( LockIn ),
    .AxiVldMask ( AxiVldMask ),
    .SelWidth ( SelWidth ),
    .sel_oup_t ( sel_oup_t ),
    .IdxWidth ( IdxWidth ),
    .idx_inp_t ( idx_inp_t )
  ) i_stream_omega_net (
    .*
  );

endmodule
