// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `stream_throttle` from `stream_throttle.sv`.
module stream_throttle_wrapper #(
parameter int unsigned MaxNumPending = 1,

    parameter int unsigned CntWidth = cf_math_pkg::idx_width(MaxNumPending),

    parameter type credit_t = logic [CntWidth-1:0]
) (
input  logic clk_i,

    input  logic rst_ni,


    input  logic    req_valid_i,

    output logic    req_valid_o,

    input  logic    req_ready_i,

    output logic    req_ready_o,


    input  logic    rsp_valid_i,

    input  logic    rsp_ready_i,


    input  credit_t credit_i
);

  stream_throttle #(
    .MaxNumPending ( MaxNumPending ),
    .CntWidth ( CntWidth ),
    .credit_t ( credit_t )
  ) i_stream_throttle (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .req_valid_i ( req_valid_i ),
    .req_valid_o ( req_valid_o ),
    .req_ready_i ( req_ready_i ),
    .req_ready_o ( req_ready_o ),
    .rsp_valid_i ( rsp_valid_i ),
    .rsp_ready_i ( rsp_ready_i ),
    .credit_i ( credit_i )
  );

endmodule
