// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `stream_demux` from `stream_demux.sv`.
module stream_demux_wrapper #(
  parameter int unsigned N_OUP     = 32'd1,

  parameter int unsigned LOG_N_OUP = (N_OUP > 32'd1) ? unsigned'($clog2(N_OUP)) : 1'b1
) (
  inp_valid_i,
  inp_ready_o,
  oup_sel_i,
  oup_valid_o,
  oup_ready_i
);

  typedef logic __inp_valid_i_t;
  typedef logic __inp_ready_o_t;
  typedef logic [LOG_N_OUP-1:0] __oup_sel_i_t;
  typedef logic [N_OUP-1:0] __oup_valid_o_t;
  typedef logic [N_OUP-1:0] __oup_ready_i_t;

  input logic [$bits(__inp_valid_i_t)-1:0] inp_valid_i;
  output logic [$bits(__inp_ready_o_t)-1:0] inp_ready_o;
  input logic [$bits(__oup_sel_i_t)-1:0] oup_sel_i;
  output logic [$bits(__oup_valid_o_t)-1:0] oup_valid_o;
  input logic [$bits(__oup_ready_i_t)-1:0] oup_ready_i;

  __inp_valid_i_t __inp_valid_i;
  __inp_ready_o_t __inp_ready_o;
  __oup_sel_i_t __oup_sel_i;
  __oup_valid_o_t __oup_valid_o;
  __oup_ready_i_t __oup_ready_i;

  assign __inp_valid_i = __inp_valid_i_t'(inp_valid_i);
  assign inp_ready_o = logic [$bits(__inp_ready_o_t)-1:0]'(__inp_ready_o);
  assign __oup_sel_i = __oup_sel_i_t'(oup_sel_i);
  assign oup_valid_o = logic [$bits(__oup_valid_o_t)-1:0]'(__oup_valid_o);
  assign __oup_ready_i = __oup_ready_i_t'(oup_ready_i);

  stream_demux #(
    .N_OUP ( N_OUP ),
    .LOG_N_OUP ( LOG_N_OUP )
  ) i_stream_demux (
    .inp_valid_i ( __inp_valid_i ),
    .inp_ready_o ( __inp_ready_o ),
    .oup_sel_i ( __oup_sel_i ),
    .oup_valid_o ( __oup_valid_o ),
    .oup_ready_i ( __oup_ready_i )
  );

endmodule
