// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `stream_xbar` from `stream_xbar.sv`.
module stream_xbar_wrapper #(
  parameter int unsigned NumInp      = 32'd0,

  parameter int unsigned NumOut      = 32'd0,

  parameter int unsigned DataWidth   = 32'd1,

  parameter type         payload_t   = logic [DataWidth-1:0],

  parameter bit          OutSpillReg = 1'b0,

  parameter int unsigned ExtPrio     = 1'b0,

  parameter int unsigned AxiVldRdy   = 1'b1,

  parameter int unsigned LockIn      = 1'b1,

  parameter payload_t    AxiVldMask  = '1,

  parameter int unsigned SelWidth = (NumOut > 32'd1) ? unsigned'($clog2(NumOut)) : 32'd1,

  parameter type sel_oup_t = logic[SelWidth-1:0],

  parameter int unsigned IdxWidth = (NumInp > 32'd1) ? unsigned'($clog2(NumInp)) : 32'd1,

  parameter type idx_inp_t = logic[IdxWidth-1:0]
) (
  clk_i,
  rst_ni,
  flush_i,
  rr_i,
  data_i,
  sel_i,
  valid_i,
  ready_o,
  data_o,
  idx_o,
  valid_o,
  ready_i
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __flush_i_t;
  typedef idx_inp_t [NumOut-1:0] __rr_i_t;
  typedef payload_t [NumInp-1:0] __data_i_t;
  typedef sel_oup_t [NumInp-1:0] __sel_i_t;
  typedef logic     [NumInp-1:0] __valid_i_t;
  typedef logic     [NumInp-1:0] __ready_o_t;
  typedef payload_t [NumOut-1:0] __data_o_t;
  typedef idx_inp_t [NumOut-1:0] __idx_o_t;
  typedef logic     [NumOut-1:0] __valid_o_t;
  typedef logic     [NumOut-1:0] __ready_i_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__flush_i_t)-1:0] flush_i;
  input logic [$bits(__rr_i_t)-1:0] rr_i;
  input logic [$bits(__data_i_t)-1:0] data_i;
  input logic [$bits(__sel_i_t)-1:0] sel_i;
  input logic [$bits(__valid_i_t)-1:0] valid_i;
  output logic [$bits(__ready_o_t)-1:0] ready_o;
  output logic [$bits(__data_o_t)-1:0] data_o;
  output logic [$bits(__idx_o_t)-1:0] idx_o;
  output logic [$bits(__valid_o_t)-1:0] valid_o;
  input logic [$bits(__ready_i_t)-1:0] ready_i;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __flush_i_t __flush_i;
  __rr_i_t __rr_i;
  __data_i_t __data_i;
  __sel_i_t __sel_i;
  __valid_i_t __valid_i;
  __ready_o_t __ready_o;
  __data_o_t __data_o;
  __idx_o_t __idx_o;
  __valid_o_t __valid_o;
  __ready_i_t __ready_i;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __flush_i = __flush_i_t'(flush_i);
  assign __rr_i = __rr_i_t'(rr_i);
  assign __data_i = __data_i_t'(data_i);
  assign __sel_i = __sel_i_t'(sel_i);
  assign __valid_i = __valid_i_t'(valid_i);
  assign ready_o = logic [$bits(__ready_o_t)-1:0]'(__ready_o);
  assign data_o = logic [$bits(__data_o_t)-1:0]'(__data_o);
  assign idx_o = logic [$bits(__idx_o_t)-1:0]'(__idx_o);
  assign valid_o = logic [$bits(__valid_o_t)-1:0]'(__valid_o);
  assign __ready_i = __ready_i_t'(ready_i);

  stream_xbar #(
    .NumInp ( NumInp ),
    .NumOut ( NumOut ),
    .DataWidth ( DataWidth ),
    .payload_t ( payload_t ),
    .OutSpillReg ( OutSpillReg ),
    .ExtPrio ( ExtPrio ),
    .AxiVldRdy ( AxiVldRdy ),
    .LockIn ( LockIn ),
    .AxiVldMask ( AxiVldMask ),
    .SelWidth ( SelWidth ),
    .sel_oup_t ( sel_oup_t ),
    .IdxWidth ( IdxWidth ),
    .idx_inp_t ( idx_inp_t )
  ) i_stream_xbar (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .flush_i ( __flush_i ),
    .rr_i ( __rr_i ),
    .data_i ( __data_i ),
    .sel_i ( __sel_i ),
    .valid_i ( __valid_i ),
    .ready_o ( __ready_o ),
    .data_o ( __data_o ),
    .idx_o ( __idx_o ),
    .valid_o ( __valid_o ),
    .ready_i ( __ready_i )
  );

endmodule
