// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `stream_fork_dynamic` from `stream_fork_dynamic.sv`.
module stream_fork_dynamic_wrapper #(
parameter int unsigned N_OUP = 32'd0
) (
input  logic             clk_i,

  input  logic             rst_ni,

  input  logic             valid_i,

  output logic             ready_o,

  input  logic [N_OUP-1:0] sel_i,

  input  logic             sel_valid_i,

  output logic             sel_ready_o,

  output logic [N_OUP-1:0] valid_o,

  input  logic [N_OUP-1:0] ready_i
);

  stream_fork_dynamic #(
    .N_OUP ( N_OUP )
  ) i_stream_fork_dynamic (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .valid_i ( valid_i ),
    .ready_o ( ready_o ),
    .sel_i ( sel_i ),
    .sel_valid_i ( sel_valid_i ),
    .sel_ready_o ( sel_ready_o ),
    .valid_o ( valid_o ),
    .ready_i ( ready_i )
  );

endmodule
