// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `stream_fifo` from `stream_fifo.sv`.
module stream_fifo_wrapper #(
parameter bit          FALL_THROUGH = 1'b0,

    parameter int unsigned DATA_WIDTH   = 32,

    parameter int unsigned DEPTH        = 8,
    parameter type         T            = logic [DATA_WIDTH-1:0],

    parameter int unsigned ADDR_DEPTH  = (DEPTH > 1) ? $clog2(DEPTH) : 1
) (
input  logic                  clk_i,
    input  logic                  rst_ni,
    input  logic                  flush_i,
    input  logic                  testmode_i,
    output logic [ADDR_DEPTH-1:0] usage_o,

    input  T                      data_i,
    input  logic                  valid_i,
    output logic                  ready_o,

    output T                      data_o,
    output logic                  valid_o,
    input  logic                  ready_i
);

  stream_fifo #(
    .FALL_THROUGH ( FALL_THROUGH ),
    .DATA_WIDTH ( DATA_WIDTH ),
    .DEPTH ( DEPTH ),
    .T ( T ),
    .ADDR_DEPTH ( ADDR_DEPTH )
  ) i_stream_fifo (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .flush_i ( flush_i ),
    .testmode_i ( testmode_i ),
    .usage_o ( usage_o ),
    .data_i ( data_i ),
    .valid_i ( valid_i ),
    .ready_o ( ready_o ),
    .data_o ( data_o ),
    .valid_o ( valid_o ),
    .ready_i ( ready_i )
  );

endmodule
