// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `stream_to_mem` from `stream_to_mem.sv`.
module stream_to_mem_wrapper #(
parameter type         mem_req_t  = logic,

  parameter type         mem_resp_t = logic,





  parameter int unsigned BufDepth   = 32'd1
) (
input  logic      clk_i,

  input  logic      rst_ni,

  input  mem_req_t  req_i,

  input  logic      req_valid_i,

  output logic      req_ready_o,

  output mem_resp_t resp_o,

  output logic      resp_valid_o,

  input  logic      resp_ready_i,

  output mem_req_t  mem_req_o,

  output logic      mem_req_valid_o,

  input  logic      mem_req_ready_i,

  input  mem_resp_t mem_resp_i,

  input  logic      mem_resp_valid_i
);

  stream_to_mem #(
    .mem_req_t ( mem_req_t ),
    .mem_resp_t ( mem_resp_t ),
    .BufDepth ( BufDepth )
  ) i_stream_to_mem (
    .*
  );

endmodule
