// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `stream_mux` from `stream_mux.sv`.
module stream_mux_wrapper #(
parameter type DATA_T = logic,
  parameter integer N_INP = 0,

  parameter integer SEL_WIDTH = cf_math_pkg::idx_width(N_INP)
) (
input  DATA_T [N_INP-1:0]     inp_data_i,
  input  logic  [N_INP-1:0]     inp_valid_i,
  output logic  [N_INP-1:0]     inp_ready_o,

  input  logic  [SEL_WIDTH-1:0] inp_sel_i,

  output DATA_T                 oup_data_o,
  output logic                  oup_valid_o,
  input  logic                  oup_ready_i
);

  stream_mux #(
    .DATA_T ( DATA_T ),
    .N_INP ( N_INP ),
    .SEL_WIDTH ( SEL_WIDTH )
  ) i_stream_mux (
    .*
  );

endmodule
