// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `stream_throttle` from `stream_throttle.sv`.
module stream_throttle_wrapper #(
    parameter int unsigned MaxNumPending = 1,

    parameter int unsigned CntWidth = cf_math_pkg::idx_width(MaxNumPending),

    parameter type credit_t = logic [CntWidth-1:0]
) (
  clk_i,
  rst_ni,
  req_valid_i,
  req_valid_o,
  req_ready_i,
  req_ready_o,
  rsp_valid_i,
  rsp_ready_i,
  credit_i
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __req_valid_i_t;
  typedef logic __req_valid_o_t;
  typedef logic __req_ready_i_t;
  typedef logic __req_ready_o_t;
  typedef logic __rsp_valid_i_t;
  typedef logic __rsp_ready_i_t;
  typedef credit_t __credit_i_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__req_valid_i_t)-1:0] req_valid_i;
  output logic [$bits(__req_valid_o_t)-1:0] req_valid_o;
  input logic [$bits(__req_ready_i_t)-1:0] req_ready_i;
  output logic [$bits(__req_ready_o_t)-1:0] req_ready_o;
  input logic [$bits(__rsp_valid_i_t)-1:0] rsp_valid_i;
  input logic [$bits(__rsp_ready_i_t)-1:0] rsp_ready_i;
  input logic [$bits(__credit_i_t)-1:0] credit_i;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __req_valid_i_t __req_valid_i;
  __req_valid_o_t __req_valid_o;
  __req_ready_i_t __req_ready_i;
  __req_ready_o_t __req_ready_o;
  __rsp_valid_i_t __rsp_valid_i;
  __rsp_ready_i_t __rsp_ready_i;
  __credit_i_t __credit_i;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __req_valid_i = __req_valid_i_t'(req_valid_i);
  assign req_valid_o = logic [$bits(__req_valid_o_t)-1:0]'(__req_valid_o);
  assign __req_ready_i = __req_ready_i_t'(req_ready_i);
  assign req_ready_o = logic [$bits(__req_ready_o_t)-1:0]'(__req_ready_o);
  assign __rsp_valid_i = __rsp_valid_i_t'(rsp_valid_i);
  assign __rsp_ready_i = __rsp_ready_i_t'(rsp_ready_i);
  assign __credit_i = __credit_i_t'(credit_i);

  stream_throttle #(
    .MaxNumPending ( MaxNumPending ),
    .CntWidth ( CntWidth ),
    .credit_t ( credit_t )
  ) i_stream_throttle (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .req_valid_i ( __req_valid_i ),
    .req_valid_o ( __req_valid_o ),
    .req_ready_i ( __req_ready_i ),
    .req_ready_o ( __req_ready_o ),
    .rsp_valid_i ( __rsp_valid_i ),
    .rsp_ready_i ( __rsp_ready_i ),
    .credit_i ( __credit_i )
  );

endmodule
