// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `stream_to_mem` from `stream_to_mem.sv`.
module stream_to_mem_wrapper #(
  parameter type         mem_req_t  = logic,

  parameter type         mem_resp_t = logic,

  parameter int unsigned BufDepth   = 32'd1
) (
  clk_i,
  rst_ni,
  req_i,
  req_valid_i,
  req_ready_o,
  resp_o,
  resp_valid_o,
  resp_ready_i,
  mem_req_o,
  mem_req_valid_o,
  mem_req_ready_i,
  mem_resp_i,
  mem_resp_valid_i
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef mem_req_t __req_i_t;
  typedef logic __req_valid_i_t;
  typedef logic __req_ready_o_t;
  typedef mem_resp_t __resp_o_t;
  typedef logic __resp_valid_o_t;
  typedef logic __resp_ready_i_t;
  typedef mem_req_t __mem_req_o_t;
  typedef logic __mem_req_valid_o_t;
  typedef logic __mem_req_ready_i_t;
  typedef mem_resp_t __mem_resp_i_t;
  typedef logic __mem_resp_valid_i_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__req_i_t)-1:0] req_i;
  input logic [$bits(__req_valid_i_t)-1:0] req_valid_i;
  output logic [$bits(__req_ready_o_t)-1:0] req_ready_o;
  output logic [$bits(__resp_o_t)-1:0] resp_o;
  output logic [$bits(__resp_valid_o_t)-1:0] resp_valid_o;
  input logic [$bits(__resp_ready_i_t)-1:0] resp_ready_i;
  output logic [$bits(__mem_req_o_t)-1:0] mem_req_o;
  output logic [$bits(__mem_req_valid_o_t)-1:0] mem_req_valid_o;
  input logic [$bits(__mem_req_ready_i_t)-1:0] mem_req_ready_i;
  input logic [$bits(__mem_resp_i_t)-1:0] mem_resp_i;
  input logic [$bits(__mem_resp_valid_i_t)-1:0] mem_resp_valid_i;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __req_i_t __req_i;
  __req_valid_i_t __req_valid_i;
  __req_ready_o_t __req_ready_o;
  __resp_o_t __resp_o;
  __resp_valid_o_t __resp_valid_o;
  __resp_ready_i_t __resp_ready_i;
  __mem_req_o_t __mem_req_o;
  __mem_req_valid_o_t __mem_req_valid_o;
  __mem_req_ready_i_t __mem_req_ready_i;
  __mem_resp_i_t __mem_resp_i;
  __mem_resp_valid_i_t __mem_resp_valid_i;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __req_i = __req_i_t'(req_i);
  assign __req_valid_i = __req_valid_i_t'(req_valid_i);
  assign req_ready_o = logic [$bits(__req_ready_o_t)-1:0]'(__req_ready_o);
  assign resp_o = logic [$bits(__resp_o_t)-1:0]'(__resp_o);
  assign resp_valid_o = logic [$bits(__resp_valid_o_t)-1:0]'(__resp_valid_o);
  assign __resp_ready_i = __resp_ready_i_t'(resp_ready_i);
  assign mem_req_o = logic [$bits(__mem_req_o_t)-1:0]'(__mem_req_o);
  assign mem_req_valid_o = logic [$bits(__mem_req_valid_o_t)-1:0]'(__mem_req_valid_o);
  assign __mem_req_ready_i = __mem_req_ready_i_t'(mem_req_ready_i);
  assign __mem_resp_i = __mem_resp_i_t'(mem_resp_i);
  assign __mem_resp_valid_i = __mem_resp_valid_i_t'(mem_resp_valid_i);

  stream_to_mem #(
    .mem_req_t ( mem_req_t ),
    .mem_resp_t ( mem_resp_t ),
    .BufDepth ( BufDepth )
  ) i_stream_to_mem (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .req_i ( __req_i ),
    .req_valid_i ( __req_valid_i ),
    .req_ready_o ( __req_ready_o ),
    .resp_o ( __resp_o ),
    .resp_valid_o ( __resp_valid_o ),
    .resp_ready_i ( __resp_ready_i ),
    .mem_req_o ( __mem_req_o ),
    .mem_req_valid_o ( __mem_req_valid_o ),
    .mem_req_ready_i ( __mem_req_ready_i ),
    .mem_resp_i ( __mem_resp_i ),
    .mem_resp_valid_i ( __mem_resp_valid_i )
  );

endmodule
