// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `stream_xbar` from `stream_xbar.sv`.
module stream_xbar_wrapper #(
parameter int unsigned NumInp      = 32'd0,
  parameter int unsigned NumOut      = 32'd0,
  parameter int unsigned DataWidth   = 32'd1,
  parameter int unsigned payload_t_WIDTH = 1,
  parameter bit          OutSpillReg = 1'b0,
  parameter int unsigned ExtPrio     = 1'b0,
  parameter int unsigned AxiVldRdy   = 1'b1,
  parameter int unsigned LockIn      = 1'b1,
  parameter payload_t    AxiVldMask  = '1,
  parameter int unsigned SelWidth = (NumOut > 32'd1) ? unsigned'($clog2(NumOut)) : 32'd1,
  parameter int unsigned sel_oup_t_WIDTH = 1,
  parameter int unsigned IdxWidth = (NumInp > 32'd1) ? unsigned'($clog2(NumInp)) : 32'd1,
  parameter int unsigned idx_inp_t_WIDTH = 1
) (
input  logic                  clk_i,
  input  logic                  rst_ni,
  input  logic                  flush_i,
  input  logic [idx_inp_t_WIDTH-1:0] [NumOut-1:0] rr_i,
  input  logic [payload_t_WIDTH-1:0] [NumInp-1:0] data_i,
  input  logic [sel_oup_t_WIDTH-1:0] [NumInp-1:0] sel_i,
  input  logic     [NumInp-1:0] valid_i,
  output logic     [NumInp-1:0] ready_o,
  output logic [payload_t_WIDTH-1:0] [NumOut-1:0] data_o,
  output logic [idx_inp_t_WIDTH-1:0] [NumOut-1:0] idx_o,
  output logic     [NumOut-1:0] valid_o,
  input  logic     [NumOut-1:0] ready_i
);

  stream_xbar #(
    .NumInp ( NumInp ),
    .NumOut ( NumOut ),
    .DataWidth ( DataWidth ),
    .payload_t ( logic [payload_t_WIDTH-1:0] ),
    .OutSpillReg ( OutSpillReg ),
    .ExtPrio ( ExtPrio ),
    .AxiVldRdy ( AxiVldRdy ),
    .LockIn ( LockIn ),
    .AxiVldMask ( AxiVldMask ),
    .SelWidth ( SelWidth ),
    .sel_oup_t ( logic [sel_oup_t_WIDTH-1:0] ),
    .IdxWidth ( IdxWidth ),
    .idx_inp_t ( logic [idx_inp_t_WIDTH-1:0] )
  ) i_stream_xbar (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .flush_i ( flush_i ),
    .rr_i ( rr_i ),
    .data_i ( data_i ),
    .sel_i ( sel_i ),
    .valid_i ( valid_i ),
    .ready_o ( ready_o ),
    .data_o ( data_o ),
    .idx_o ( idx_o ),
    .valid_o ( valid_o ),
    .ready_i ( ready_i )
  );

endmodule
