// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `stream_filter` from `stream_filter.sv`.
module stream_filter_wrapper (
  valid_i,
  ready_o,
  drop_i,
  valid_o,
  ready_i
);

  typedef logic __valid_i_t;
  typedef logic __ready_o_t;
  typedef logic __drop_i_t;
  typedef logic __valid_o_t;
  typedef logic __ready_i_t;

  input logic [$bits(__valid_i_t)-1:0] valid_i;
  output logic [$bits(__ready_o_t)-1:0] ready_o;
  input logic [$bits(__drop_i_t)-1:0] drop_i;
  output logic [$bits(__valid_o_t)-1:0] valid_o;
  input logic [$bits(__ready_i_t)-1:0] ready_i;

  __valid_i_t __valid_i;
  __ready_o_t __ready_o;
  __drop_i_t __drop_i;
  __valid_o_t __valid_o;
  __ready_i_t __ready_i;

  assign __valid_i = __valid_i_t'(valid_i);
  assign ready_o = logic [$bits(__ready_o_t)-1:0]'(__ready_o);
  assign __drop_i = __drop_i_t'(drop_i);
  assign valid_o = logic [$bits(__valid_o_t)-1:0]'(__valid_o);
  assign __ready_i = __ready_i_t'(ready_i);

  stream_filter i_stream_filter (
    .valid_i ( __valid_i ),
    .ready_o ( __ready_o ),
    .drop_i ( __drop_i ),
    .valid_o ( __valid_o ),
    .ready_i ( __ready_i )
  );

endmodule
