// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `stream_join_dynamic` from `stream_join_dynamic.sv`.
module stream_join_dynamic_wrapper #(
  parameter int unsigned N_INP = 32'd0
) (
  inp_valid_i,
  inp_ready_o,
  sel_i,
  oup_valid_o,
  oup_ready_i
);

  typedef logic [N_INP-1:0] __inp_valid_i_t;
  typedef logic [N_INP-1:0] __inp_ready_o_t;
  typedef logic [N_INP-1:0] __sel_i_t;
  typedef logic __oup_valid_o_t;
  typedef logic __oup_ready_i_t;

  input logic [$bits(__inp_valid_i_t)-1:0] inp_valid_i;
  output logic [$bits(__inp_ready_o_t)-1:0] inp_ready_o;
  input logic [$bits(__sel_i_t)-1:0] sel_i;
  output logic [$bits(__oup_valid_o_t)-1:0] oup_valid_o;
  input logic [$bits(__oup_ready_i_t)-1:0] oup_ready_i;

  __inp_valid_i_t __inp_valid_i;
  __inp_ready_o_t __inp_ready_o;
  __sel_i_t __sel_i;
  __oup_valid_o_t __oup_valid_o;
  __oup_ready_i_t __oup_ready_i;

  assign __inp_valid_i = __inp_valid_i_t'(inp_valid_i);
  assign inp_ready_o = logic [$bits(__inp_ready_o_t)-1:0]'(__inp_ready_o);
  assign __sel_i = __sel_i_t'(sel_i);
  assign oup_valid_o = logic [$bits(__oup_valid_o_t)-1:0]'(__oup_valid_o);
  assign __oup_ready_i = __oup_ready_i_t'(oup_ready_i);

  stream_join_dynamic #(
    .N_INP ( N_INP )
  ) i_stream_join_dynamic (
    .inp_valid_i ( __inp_valid_i ),
    .inp_ready_o ( __inp_ready_o ),
    .sel_i ( __sel_i ),
    .oup_valid_o ( __oup_valid_o ),
    .oup_ready_i ( __oup_ready_i )
  );

endmodule
