// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `sub_per_hash` from `sub_per_hash.sv`.
module sub_per_hash_wrapper #(
  parameter int unsigned InpWidth   = 32'd11,
  parameter int unsigned HashWidth  = 32'd5,
  parameter int unsigned NoRounds   = 32'd1,
  parameter int unsigned PermuteKey = 32'd299034753,
  parameter int unsigned XorKey     = 32'd4094834
) (
  data_i,
  hash_o,
  hash_onehot_o
);

  typedef logic [InpWidth-1:0] __data_i_t;
  typedef logic [HashWidth-1:0] __hash_o_t;
  typedef logic [2**HashWidth-1:0] __hash_onehot_o_t;

  input logic [$bits(__data_i_t)-1:0] data_i;
  output logic [$bits(__hash_o_t)-1:0] hash_o;
  output logic [$bits(__hash_onehot_o_t)-1:0] hash_onehot_o;

  __data_i_t __data_i;
  __hash_o_t __hash_o;
  __hash_onehot_o_t __hash_onehot_o;

  assign __data_i = __data_i_t'(data_i);
  assign hash_o = logic [$bits(__hash_o_t)-1:0]'(__hash_o);
  assign hash_onehot_o = logic [$bits(__hash_onehot_o_t)-1:0]'(__hash_onehot_o);

  sub_per_hash #(
    .InpWidth ( InpWidth ),
    .HashWidth ( HashWidth ),
    .NoRounds ( NoRounds ),
    .PermuteKey ( PermuteKey ),
    .XorKey ( XorKey )
  ) i_sub_per_hash (
    .data_i ( __data_i ),
    .hash_o ( __hash_o ),
    .hash_onehot_o ( __hash_onehot_o )
  );

endmodule
