// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `sync` from `sync.sv`.
module sync_wrapper #(
    parameter int unsigned STAGES = 2,
    parameter bit ResetValue = 1'b0
) (
  clk_i,
  rst_ni,
  serial_i,
  serial_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __serial_i_t;
  typedef logic __serial_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__serial_i_t)-1:0] serial_i;
  output logic [$bits(__serial_o_t)-1:0] serial_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __serial_i_t __serial_i;
  __serial_o_t __serial_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __serial_i = __serial_i_t'(serial_i);
  assign serial_o = logic [$bits(__serial_o_t)-1:0]'(__serial_o);

  sync #(
    .STAGES ( STAGES ),
    .ResetValue ( ResetValue )
  ) i_sync (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .serial_i ( __serial_i ),
    .serial_o ( __serial_o )
  );

endmodule
