// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `sync_wedge` from `sync_wedge.sv`.
module sync_wedge_wrapper #(
    parameter int unsigned STAGES = 2
) (
  clk_i,
  rst_ni,
  en_i,
  serial_i,
  r_edge_o,
  f_edge_o,
  serial_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __en_i_t;
  typedef logic __serial_i_t;
  typedef logic __r_edge_o_t;
  typedef logic __f_edge_o_t;
  typedef logic __serial_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__en_i_t)-1:0] en_i;
  input logic [$bits(__serial_i_t)-1:0] serial_i;
  output logic [$bits(__r_edge_o_t)-1:0] r_edge_o;
  output logic [$bits(__f_edge_o_t)-1:0] f_edge_o;
  output logic [$bits(__serial_o_t)-1:0] serial_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __en_i_t __en_i;
  __serial_i_t __serial_i;
  __r_edge_o_t __r_edge_o;
  __f_edge_o_t __f_edge_o;
  __serial_o_t __serial_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __en_i = __en_i_t'(en_i);
  assign __serial_i = __serial_i_t'(serial_i);
  assign r_edge_o = logic [$bits(__r_edge_o_t)-1:0]'(__r_edge_o);
  assign f_edge_o = logic [$bits(__f_edge_o_t)-1:0]'(__f_edge_o);
  assign serial_o = logic [$bits(__serial_o_t)-1:0]'(__serial_o);

  sync_wedge #(
    .STAGES ( STAGES )
  ) i_sync_wedge (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .en_i ( __en_i ),
    .serial_i ( __serial_i ),
    .r_edge_o ( __r_edge_o ),
    .f_edge_o ( __f_edge_o ),
    .serial_o ( __serial_o )
  );

endmodule
