// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager wrapper for `sync_wedge` from `sync_wedge.sv`.
module sync_wedge_wrapper #(
parameter int unsigned STAGES = 2
) (
input  logic clk_i,
  input  logic rst_ni,
  input  logic en_i,
  input  logic serial_i,
  output logic r_edge_o,
  output logic f_edge_o,
  output logic serial_o
);

  sync_wedge #(
    .STAGES ( STAGES )
  ) i_sync_wedge (
    .clk_i ( clk_i ),
    .rst_ni ( rst_ni ),
    .en_i ( en_i ),
    .serial_i ( serial_i ),
    .r_edge_o ( r_edge_o ),
    .f_edge_o ( f_edge_o ),
    .serial_o ( serial_o )
  );

endmodule
