// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `trip_counter` from `trip_counter.sv`.
module trip_counter_wrapper #(
    parameter int unsigned WIDTH = 4
) (
  clk_i,
  rst_ni,
  en_i,
  delta_i,
  bound_i,
  q_o,
  last_o,
  trip_o
);

  typedef logic __clk_i_t;
  typedef logic __rst_ni_t;
  typedef logic __en_i_t;
  typedef logic [WIDTH-1:0] __delta_i_t;
  typedef logic [WIDTH-1:0] __bound_i_t;
  typedef logic [WIDTH-1:0] __q_o_t;
  typedef logic __last_o_t;
  typedef logic __trip_o_t;

  input logic [$bits(__clk_i_t)-1:0] clk_i;
  input logic [$bits(__rst_ni_t)-1:0] rst_ni;
  input logic [$bits(__en_i_t)-1:0] en_i;
  input logic [$bits(__delta_i_t)-1:0] delta_i;
  input logic [$bits(__bound_i_t)-1:0] bound_i;
  output logic [$bits(__q_o_t)-1:0] q_o;
  output logic [$bits(__last_o_t)-1:0] last_o;
  output logic [$bits(__trip_o_t)-1:0] trip_o;

  __clk_i_t __clk_i;
  __rst_ni_t __rst_ni;
  __en_i_t __en_i;
  __delta_i_t __delta_i;
  __bound_i_t __bound_i;
  __q_o_t __q_o;
  __last_o_t __last_o;
  __trip_o_t __trip_o;

  assign __clk_i = __clk_i_t'(clk_i);
  assign __rst_ni = __rst_ni_t'(rst_ni);
  assign __en_i = __en_i_t'(en_i);
  assign __delta_i = __delta_i_t'(delta_i);
  assign __bound_i = __bound_i_t'(bound_i);
  assign q_o = logic [$bits(__q_o_t)-1:0]'(__q_o);
  assign last_o = logic [$bits(__last_o_t)-1:0]'(__last_o);
  assign trip_o = logic [$bits(__trip_o_t)-1:0]'(__trip_o);

  trip_counter #(
    .WIDTH ( WIDTH )
  ) i_trip_counter (
    .clk_i ( __clk_i ),
    .rst_ni ( __rst_ni ),
    .en_i ( __en_i ),
    .delta_i ( __delta_i ),
    .bound_i ( __bound_i ),
    .q_o ( __q_o ),
    .last_o ( __last_o ),
    .trip_o ( __trip_o )
  );

endmodule
