// Copyright 2018 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

// Auto-generated by scripts/generate_ip_wrappers.py; do not edit manually.
// AMD Vivado IP packager flat-port wrapper for `unread` from `unread.sv`.
module unread_wrapper (
  d_i
);

  typedef logic __d_i_t;

  input logic [$bits(__d_i_t)-1:0] d_i;

  __d_i_t __d_i;

  assign __d_i = __d_i_t'(d_i);

  unread i_unread (
    .d_i ( __d_i )
  );

endmodule
